from __future__ import annotations


def bridge_columns_for_table(
    table_name: str,
    *,
    error_type: type[ValueError],
) -> tuple[str, ...]:
    columns_by_table = {
        "Factions": (
            "id",
            "name",
            "content_scope",
            "faction_keywords",
            "army_rule_id",
            "army_rule_name",
            "source_ids",
        ),
        "Datasheets": (
            "id",
            "name",
            "content_scope",
            "keywords",
            "faction_keywords",
            "legend",
            "loadout",
            "transport",
            "leader_head",
            "leader_footer",
            "damaged_description",
            "damaged_effects",
            "max_unit_models",
            "source_ids",
        ),
        "Datasheets_models": (
            "datasheet_id",
            "line",
            "name",
            "model_profile_id",
            "content_scope",
            "m",
            "t",
            "sv",
            "inv_sv",
            "w",
            "ld",
            "oc",
            "ws",
            "bs",
            "min_models",
            "max_models",
            "allows_zero_models",
            "base_size",
            "base_size_source_id",
            "base_size_document_reference",
            "height",
            "height_units",
            "height_source_id",
            "height_document_reference",
            "height_reviewer_status",
            "height_evidence_kind",
            "source_ids",
        ),
        "Datasheets_wargear": (
            "datasheet_id",
            "line",
            "line_in_wargear",
            "name",
            "wargear_id",
            "weapon_profile_id",
            "model_profile_ids",
            "range",
            "a",
            "skill_characteristic",
            "skill",
            "s",
            "ap",
            "d",
            "weapon_keywords",
            "weapon_abilities",
            "default_loadout",
            "default_wargear_count",
            "source_ids",
        ),
        "Datasheets_options": (
            "datasheet_id",
            "line",
            "description",
            "option_id",
            "model_profile_id",
            "default_wargear_ids",
            "allowed_wargear_ids",
            "min_selections",
            "max_selections",
            "condition_kind",
            "condition_wargear_ids",
            "selection_group_id",
            "selection_models_per_increment",
            "selection_group_max_per_increment",
            "selection_option_max_per_increment",
            "effect_kind",
            "effect_wargear_id",
            "effect_replaced_wargear_id",
            "effect_model_count",
            "effect_wargear_count",
            "unit_resource_kind",
            "unit_resource_amount_per_selection",
            "source_ids",
        ),
        "Datasheets_mustering_options": (
            "datasheet_id",
            "line",
            "description",
            "option_id",
            "selection_group_id",
            "label",
            "model_profile_id",
            "required",
            "effect_kind",
            "effect_keyword",
            "effect_wargear_id",
            "effect_model_count",
            "effect_wargear_count",
            "source_ids",
        ),
        "Datasheets_abilities": (
            "datasheet_id",
            "line",
            "ability_id",
            "name",
            "description",
            "parameter",
            "type",
            "support",
            "source_kind",
            "effect_description",
            "source_wargear_id",
            "rule_ir_payload",
            "rule_ir_diagnostics",
            "timing_tags",
            "parameter_tokens",
            "source_ids",
        ),
        "Datasheets_leader": (
            "leader_id",
            "attached_id",
            "required_wargear_ids",
            "source_ids",
        ),
        "Datasheets_unit_composition": (
            "datasheet_id",
            "line",
            "description",
            "source_ids",
        ),
    }
    columns = columns_by_table.get(table_name)
    if columns is None:
        raise error_type("Unsupported bridge output table.")
    return columns
