# ruff: noqa: F403,F405,I001
# pyright: reportUnknownVariableType=false
from __future__ import annotations

from warhammer40k_core.engine import (
    attack_sequence_damage_resolution as attack_sequence_damage_resolution,
    attack_sequence_destroyed_transport as attack_sequence_destroyed_transport,
    attack_sequence_dice_rerolls as attack_sequence_dice_rerolls,
    attack_sequence_dispatch as attack_sequence_dispatch,
    attack_sequence_geometry_targets as attack_sequence_geometry_targets,
    attack_sequence_group_selection as attack_sequence_group_selection,
    attack_sequence_grouped_allocation as attack_sequence_grouped_allocation,
    attack_sequence_hazardous as attack_sequence_hazardous,
    attack_sequence_hit_wound as attack_sequence_hit_wound,
    attack_sequence_model as attack_sequence_model,
    attack_sequence_psychic_modifiers as attack_sequence_psychic_modifiers,
    attack_sequence_selection as attack_sequence_selection,
    attack_sequence_state as attack_sequence_state,
    attack_sequence_validation as attack_sequence_validation,
)
from warhammer40k_core.engine.attack_sequence_bindings import bind_attack_sequence_modules
from warhammer40k_core.engine.attack_sequence_damage_resolution import *
from warhammer40k_core.engine.attack_sequence_destroyed_transport import *
from warhammer40k_core.engine.attack_sequence_dice_rerolls import *
from warhammer40k_core.engine.attack_sequence_dispatch import *
from warhammer40k_core.engine.attack_sequence_geometry_targets import *
from warhammer40k_core.engine.attack_sequence_group_selection import *
from warhammer40k_core.engine.attack_sequence_grouped_allocation import *
from warhammer40k_core.engine.attack_sequence_hazardous import *
from warhammer40k_core.engine.attack_sequence_hit_wound import *
from warhammer40k_core.engine.attack_sequence_model import *
from warhammer40k_core.engine.attack_sequence_psychic_modifiers import *
from warhammer40k_core.engine.attack_sequence_selection import *
from warhammer40k_core.engine.attack_sequence_state import *
from warhammer40k_core.engine.attack_sequence_validation import *

bind_attack_sequence_modules()

__all__ = (
    "ATTACK_ALLOCATION_DECISION_TYPES",
    "ATTACK_RESOLUTION_SELECTION_DECISION_TYPES",
    "DAMAGE_ALLOCATION_RULE_ID",
    "DEADLY_DEMISE_SOURCE_KIND",
    "HAZARDOUS_SOURCE_KIND",
    "IGNORE_ALL_MODIFIERS_OPTION_ID",
    "IGNORE_BENEFICIAL_MODIFIERS_OPTION_ID",
    "IGNORE_DETRIMENTAL_MODIFIERS_OPTION_ID",
    "KEEP_ALL_MODIFIERS_OPTION_ID",
    "SELECT_ATTACK_WEAPON_GROUP_DECISION_TYPE",
    "SELECT_PSYCHIC_ATTACK_MODIFIER_IGNORES_DECISION_TYPE",
    "SELECT_RESOLVE_TARGET_UNIT_DECISION_TYPE",
    "SOURCE_BACKED_ATTACK_REROLL_ROLL_STATE_KEYS",
    "_PRECISION_CHARACTER_GROUP_ROLES",
    "AttackModifierStackSet",
    "AttackModifierStackSetPayload",
    "AttackResolutionContextPayload",
    "AttackSequence",
    "AttackSequenceEvent",
    "AttackSequenceEventHandler",
    "AttackSequenceEventPayload",
    "AttackSequenceHooks",
    "AttackSequencePayload",
    "AttackSequenceStep",
    "DeferredMortalWounds",
    "DeferredMortalWoundsPayload",
    "DestroyedModelEmission",
    "DestructionReactionContextPayload",
    "FastDiceGroup",
    "FastDiceGroupPayload",
    "GatheredAttackContribution",
    "GatheredAttackContributionPayload",
    "GatheredAttackGroup",
    "GatheredAttackGroupPayload",
    "HazardousMortalWoundSourceContextPayload",
    "HitRoll",
    "HitRollPayload",
    "IdenticalAttackSignature",
    "IdenticalAttackSignaturePayload",
    "LostWoundContextPayload",
    "PendingDestroyedTransportDisembark",
    "PendingDestroyedTransportDisembarkPayload",
    "PendingGroupedDamage",
    "PendingGroupedDamagePayload",
    "PrecisionPoolSelection",
    "PsychicAttackModifierIgnoreSelection",
    "SaveDieEntryPayload",
    "WoundRoll",
    "WoundRollPayload",
    "_advance_after_current_pool",
    "_advance_after_resolved_hit",
    "_alive_allocated_model_ids",
    "_alive_allocated_model_ids_for_target_unit",
    "_append_replay_resume_unique_event_once",
    "_apply_damage_after_feel_no_pain",
    "_apply_deferred_mortal_wound_feel_no_pain_decision",
    "_apply_deferred_mortal_wounds",
    "_apply_valid_destroyed_transport_disembark",
    "_attack_context_matches_pending_grouped_damage",
    "_attack_sequence_for_context",
    "_battlefield_scenario_for_attack_sequence",
    "_begin_destroyed_transport_disembark_if_needed",
    "_benefit_of_cover_ballistic_skill_penalty",
    "_build_precision_allocation_request",
    "_canonical_keyword",
    "_cap_roll_modifier",
    "_command_reroll_opportunity_boundary_state_payload",
    "_command_reroll_opportunity_option",
    "_command_reroll_opportunity_options",
    "_command_reroll_opportunity_state_hash",
    "_command_reroll_opportunity_window",
    "_conditional_wound_full_reroll_applies",
    "_continue_after_grouped_allocation_order",
    "_continue_deadly_demise_after_mortal_wound_feel_no_pain",
    "_continue_deadly_demise_after_secondary_destruction_reaction",
    "_continue_grouped_allocation_for_wound_contexts",
    "_continue_grouped_damage_after_interruption",
    "_continue_hazardous_after_mortal_wound_feel_no_pain",
    "_continue_pending_destroyed_transport_disembark",
    "_cover_for_allocated_model",
    "_cover_result_with_effect_source",
    "_current_allocation_group_for_order",
    "_current_model_id_for_allocation_group",
    "_damage_value",
    "_deadly_demise_attack_context_from_source_context",
    "_deadly_demise_descriptor",
    "_deadly_demise_mortal_wounds_for_target",
    "_deadly_demise_secondary_continuation_payload",
    "_deadly_demise_source_context_payload",
    "_deadly_demise_target_unit_ids",
    "_defer_grouped_devastating_wounds",
    "_destroyed_damage_applications",
    "_destroyed_model_placement_payload",
    "_destroyed_model_removal_record",
    "_destroyed_transport_cargo_state_for_damage",
    "_destroyed_transport_placement",
    "_destroyed_transport_placement_invalid_status",
    "_destroyed_transport_proposal_invalid_status",
    "_destroyed_transport_proposal_parse_failure",
    "_destruction_reaction_action_host",
    "_destruction_reaction_context_from_payload",
    "_destruction_reaction_context_payload",
    "_destruction_reaction_status_if_needed",
    "_destruction_reaction_trigger_threshold",
    "_devastating_wounds_resolution_for_attack",
    "_dice_rolled_event_id_for_roll",
    "_emit_damage_event",
    "_emit_deadly_demise_mortal_wounds_applied",
    "_emit_deferred_mortal_wounds_applied",
    "_emit_event",
    "_emit_grouped_allocation_event",
    "_emit_grouped_save_die_event",
    "_emit_hazardous_mortal_wounds_applied",
    "_emit_hazardous_test_resolved",
    "_emit_mandatory_destruction_reaction_record",
    "_fast_dice_pool_key",
    "_feel_no_pain_source_applies_to_attack",
    "_feel_no_pain_sources_for_attack",
    "_first_allocation_group",
    "_first_allocation_group_order",
    "_first_unresolved_pool_index",
    "_first_unresolved_pool_index_for_target",
    "_first_unresolved_pool_index_for_target_from",
    "_first_unresolved_pool_index_from",
    "_gathered_attack_contribution",
    "_gathered_attack_group_from_indices",
    "_gathered_attack_group_id",
    "_grouped_attack_context_payload",
    "_grouped_precision_request_if_available",
    "_grouped_wounded_contexts_for_pool",
    "_has_beneficial_psychic_modifier",
    "_has_detrimental_psychic_modifier",
    "_hazardous_feel_no_pain_status",
    "_hazardous_mortal_wounds_for_attacker",
    "_hazardous_source_context_from_payload",
    "_hazardous_source_context_payload",
    "_highest_toughness_for_models",
    "_hit_reroll_forbidden_rule_ids",
    "_hit_roll_modifier",
    "_hit_skill",
    "_hit_skill_modifier",
    "_is_deadly_demise_continuation",
    "_key_error_field",
    "_latest_reroll_state_for_original_roll",
    "_legal_model_ids_for_allocation_group_damage",
    "_lost_wound_context_from_payload",
    "_lost_wound_context_payload",
    "_melta_damage_modifier",
    "_missing_destroyed_transport_disembark_field",
    "_model_is_alive",
    "_nested_payload_object",
    "_no_save_damage_order_roll_spec",
    "_objective_markers_for_attack_sequence",
    "_optional_destruction_reaction_active_effect_requirement_is_met",
    "_optional_destruction_reaction_sources_after_trigger_rolls",
    "_optional_destruction_reaction_trigger_battle_round_is_current",
    "_optional_destruction_reaction_trigger_conditions_met",
    "_optional_destruction_reaction_trigger_descriptor",
    "_optional_destruction_reaction_trigger_roll_type",
    "_optional_payload_string",
    "_parse_destroyed_transport_disembark_submission_or_invalid",
    "_payload_bool",
    "_payload_identifier_tuple",
    "_payload_int",
    "_payload_object",
    "_payload_positive_int",
    "_payload_positive_number",
    "_payload_string",
    "_payload_string_list",
    "_persisting_hit_roll_modifier",
    "_plunging_fire_ballistic_skill_improvement",
    "_pool_id",
    "_pre_removal_destruction_reaction_context_payload",
    "_precision_grouped_allocation_context_and_groups",
    "_precision_pool_selection",
    "_precision_selected_group_id",
    "_precision_selected_model_ids",
    "_psychic_attack_modifier_ignore_options",
    "_psychic_attack_modifier_ignore_request",
    "_psychic_attack_modifier_ignore_selection_for_attack",
    "_random_characteristic_roll_spec",
    "_record_auto_attack_sequence_selection",
    "_remove_resolved_destroyed_transport_cargo_state",
    "_request_command_reroll_for_attack_roll_if_available",
    "_request_destroyed_transport_disembark_placement",
    "_request_destroyed_transport_disembark_placement_retry",
    "_request_source_backed_hit_reroll_if_available",
    "_request_source_backed_wound_reroll_if_available",
    "_reroll_wound_for_twin_linked_if_needed",
    "_resolve_deadly_demise_before_removal",
    "_resolve_deadly_demise_secondary_destroyed_models",
    "_resolve_destroyed_transport_disembark_submission",
    "_resolve_grouped_current_pool",
    "_resolve_grouped_damage_from",
    "_resolve_hazardous_tests",
    "_resolve_lost_wound_stage",
    "_resolve_mandatory_destruction_reactions_before_removal",
    "_resolve_target_option_id",
    "_roll_grouped_saves",
    "_roll_hit",
    "_roll_hit_and_wound",
    "_roll_or_reuse_state",
    "_roll_wound",
    "_route_deadly_demise_mortal_wounds",
    "_runtime_modifier_registry",
    "_save_options_for_allocation",
    "_save_options_with_effect_invulnerable",
    "_select_or_request_next_gathered_group",
    "_selected_anti_keyword_ability_id",
    "_selected_destruction_reaction_source_from_request",
    "_source_backed_attack_context_id_matches_active_pool",
    "_source_backed_attack_kind_for_phase",
    "_source_backed_hit_permission_for_attack",
    "_source_backed_reroll_already_answered",
    "_source_backed_wound_permission_for_attack",
    "_state_destruction_reaction_sources",
    "_state_feel_no_pain_decline_allowed",
    "_state_feel_no_pain_sources",
    "_synthetic_pool_for_gathered_group",
    "_target_has_effect_cover",
    "_target_has_effect_cover_denial",
    "_target_unit_toughness",
    "_target_unit_within_any_objective_marker_range",
    "_toughness_values_for_models",
    "_unit_has_model_within_deadly_demise_range",
    "_unit_instance_id_for_model",
    "_validate_allocation_group_payload_tuple",
    "_validate_allocation_group_tuple",
    "_validate_attack_context_matches_sequence",
    "_validate_attack_pools",
    "_validate_current_source_backed_attack_reroll_context_if_required",
    "_validate_d6_minimum_success",
    "_validate_d6_target",
    "_validate_d6_value",
    "_validate_deferred_mortal_wounds",
    "_validate_destroyed_transport_disembark_tuple",
    "_validate_destruction_reaction_source_tuple",
    "_validate_fast_dice_pools",
    "_validate_gathered_attack_contributions",
    "_validate_gathered_group_matches_attack_pools",
    "_validate_grouped_request_context_matches_sequence",
    "_validate_identifier",
    "_validate_identifier_tuple",
    "_validate_int",
    "_validate_lost_wound_context_matches_sequence",
    "_validate_non_negative_int",
    "_validate_optional_identifier",
    "_validate_ordered_allocation_group_tuple",
    "_validate_ordered_identifier_tuple",
    "_validate_pool_index_tuple",
    "_validate_pool_indices_within_attack_pools",
    "_validate_positive_int",
    "_validate_roll_modifier_tuple",
    "_validate_save_die_entry_payload",
    "_validate_save_die_entry_tuple",
    "_validate_weapon_profile_signature_shape",
    "_weapon_rule_tokens_for_signature",
    "_wound_roll_modifier",
    "apply_allocation_order_decision",
    "apply_attack_weapon_group_decision",
    "apply_damage_allocation_model_decision",
    "apply_destroyed_transport_disembark_proposal_decision",
    "apply_destruction_reaction_decision",
    "apply_feel_no_pain_decision",
    "apply_precision_allocation_decision",
    "apply_resolve_target_unit_decision",
    "apply_source_backed_attack_dice_reroll_decision",
    "attack_pool_attacker_unit_id",
    "attack_sequence_hit_roll_spec",
    "attack_sequence_step_from_token",
    "attack_sequence_wound_roll_spec",
    "build_select_attack_weapon_group_request",
    "build_select_resolve_target_unit_request",
    "cover_for_allocated_model",
    "current_legal_damage_allocation_model_ids",
    "deadly_demise_mortal_wounds_roll_spec",
    "deadly_demise_trigger_roll_spec",
    "gathered_attack_groups_for_target",
    "identical_attack_signature",
    "invalid_destroyed_transport_disembark_proposal_status",
    "is_destroyed_transport_disembark_proposal_request",
    "resolve_attack_sequence_until_blocked",
    "selected_attack_weapon_group_from_result",
    "selected_resolve_target_from_result",
    "unresolved_target_unit_ids",
    "validate_destruction_reaction_context_matches_sequence",
    "validate_psychic_attack_modifier_ignore_decision",
    "wound_roll_target_number",
)
