from __future__ import annotations

from warhammer40k_core.engine.attack_sequence import (
    SELECT_ATTACK_WEAPON_GROUP_DECISION_TYPE,
    SELECT_POST_ROLL_ATTACK_POOL_DECISION_TYPE,
    SELECT_PSYCHIC_ATTACK_MODIFIER_IGNORES_DECISION_TYPE,
    SELECT_RESOLVE_TARGET_UNIT_DECISION_TYPE,
)
from warhammer40k_core.engine.damage_allocation import (
    SELECT_ALLOCATION_ORDER_DECISION_TYPE,
    SELECT_DAMAGE_ALLOCATION_MODEL_DECISION_TYPE,
    SELECT_DESTRUCTION_REACTION_DECISION_TYPE,
    SELECT_FEEL_NO_PAIN_DECISION_TYPE,
    SELECT_PRECISION_ALLOCATION_DECISION_TYPE,
)
from warhammer40k_core.engine.dice_result_overrides import DICE_RESULT_OVERRIDE_DECISION_TYPE
from warhammer40k_core.engine.mortal_wound_model_allocation import (
    SELECT_MORTAL_WOUND_MODEL_DECISION_TYPE,
)

ATTACK_SEQUENCE_CONTEXT_BOUND_DECISION_TYPES = frozenset(
    (
        SELECT_RESOLVE_TARGET_UNIT_DECISION_TYPE,
        SELECT_ATTACK_WEAPON_GROUP_DECISION_TYPE,
        SELECT_POST_ROLL_ATTACK_POOL_DECISION_TYPE,
    )
)
ATTACK_SEQUENCE_ACTIVE_CONTINUATION_DECISION_TYPES = frozenset(
    (
        SELECT_ALLOCATION_ORDER_DECISION_TYPE,
        SELECT_DAMAGE_ALLOCATION_MODEL_DECISION_TYPE,
        SELECT_PRECISION_ALLOCATION_DECISION_TYPE,
        SELECT_FEEL_NO_PAIN_DECISION_TYPE,
        SELECT_DESTRUCTION_REACTION_DECISION_TYPE,
    )
)
ATTACK_SEQUENCE_AUTHORITY_BOUND_DECISION_TYPES = frozenset(
    (
        SELECT_MORTAL_WOUND_MODEL_DECISION_TYPE,
        SELECT_FEEL_NO_PAIN_DECISION_TYPE,
        SELECT_PSYCHIC_ATTACK_MODIFIER_IGNORES_DECISION_TYPE,
        DICE_RESULT_OVERRIDE_DECISION_TYPE,
    )
)
ATTACK_SEQUENCE_DECISION_TYPES = frozenset(
    ATTACK_SEQUENCE_CONTEXT_BOUND_DECISION_TYPES
    | ATTACK_SEQUENCE_ACTIVE_CONTINUATION_DECISION_TYPES
    | ATTACK_SEQUENCE_AUTHORITY_BOUND_DECISION_TYPES
)

__all__ = [
    "ATTACK_SEQUENCE_ACTIVE_CONTINUATION_DECISION_TYPES",
    "ATTACK_SEQUENCE_AUTHORITY_BOUND_DECISION_TYPES",
    "ATTACK_SEQUENCE_CONTEXT_BOUND_DECISION_TYPES",
    "ATTACK_SEQUENCE_DECISION_TYPES",
]
