# ruff: noqa: F401,RUF022
# pyright: reportUnusedImport=false
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, replace
from enum import StrEnum
from hashlib import sha256
from typing import TYPE_CHECKING, NotRequired, Self, TypedDict, cast

from warhammer40k_core.core.attributes import Characteristic
from warhammer40k_core.core.dice import (
    DiceExpression,
    DiceRollResult,
    DiceRollResultPayload,
    DiceRollSpec,
    DiceRollState,
    DiceRollStatePayload,
    RandomCharacteristicRoll,
    RandomCharacteristicTiming,
    RerollComponentSelectionPolicy,
    RerollPermission,
)
from warhammer40k_core.core.modifiers import (
    ModifierStack,
    ModifierStackPayload,
    RollModifier,
    RollModifierPayload,
)
from warhammer40k_core.core.objectives import ObjectiveMarker
from warhammer40k_core.core.ruleset_descriptor import (
    CoverEffect,
    LineOfSightPolicy,
    RulesetDescriptor,
    TerrainFeatureKind,
    battle_phase_kind_from_token,
)
from warhammer40k_core.core.validation import IdentifierValidator
from warhammer40k_core.core.weapon_profiles import (
    AbilityKind,
    DamageProfile,
    DamageProfilePayload,
    RangeProfileKind,
    WeaponKeyword,
    WeaponProfile,
    WeaponProfileError,
)
from warhammer40k_core.engine.allocated_attack_damage_modifiers import (
    AllocatedAttackDamageModifierContext,
)
from warhammer40k_core.engine.battlefield_state import (
    BattlefieldPlacementKind,
    BattlefieldRemovalKind,
    BattlefieldScenario,
    BattlefieldTransitionBatch,
    ModelRemovalRecord,
    PlacementError,
    UnitPlacement,
    geometry_model_for_placement,
)
from warhammer40k_core.engine.core_stratagem_effects import (
    GO_TO_GROUND_EFFECT_KIND,
    unit_effect_hit_roll_modifier,
    unit_effect_invulnerable_save,
    unit_effects_deny_benefit_of_cover,
    unit_effects_grant_benefit_of_cover,
)
from warhammer40k_core.engine.damage_allocation import (
    SELECT_ALLOCATION_ORDER_DECISION_TYPE,
    SELECT_DAMAGE_ALLOCATION_MODEL_DECISION_TYPE,
    SELECT_DESTRUCTION_REACTION_DECISION_TYPE,
    SELECT_FEEL_NO_PAIN_DECISION_TYPE,
    SELECT_PRECISION_ALLOCATION_DECISION_TYPE,
    AllocationGroup,
    AllocationGroupPayload,
    AllocationGroupRole,
    AllocationOrderDecision,
    AttackAllocation,
    AttackAllocationConstraint,
    AttackAllocationPayload,
    AttackAllocationRuleContext,
    AttackAllocationRuleContextPayload,
    DamageAllocationModelDecision,
    DamageApplication,
    DamageApplicationPayload,
    DamageKind,
    DestructionReactionDecision,
    DestructionReactionKind,
    DestructionReactionSource,
    DestructionReactionSourcePayload,
    FeelNoPainAttackCondition,
    FeelNoPainDecision,
    FeelNoPainResolution,
    FeelNoPainResolutionPayload,
    FeelNoPainSource,
    FeelNoPainSourcePayload,
    MortalWoundApplication,
    MortalWoundApplicationProgress,
    MortalWoundRoutingResult,
    allocation_context_for_unit,
    allocation_groups_for_context,
    apply_damage_to_model,
    build_allocation_order_request,
    build_damage_allocation_model_request,
    build_destruction_reaction_request,
    build_feel_no_pain_request,
    continue_mortal_wound_application,
    damage_kind_from_token,
    is_mortal_wound_feel_no_pain_request,
    legal_allocation_group_orders,
    model_by_id,
    remove_destroyed_model_from_battlefield,
    resolve_feel_no_pain_rolls,
    resolve_mortal_wound_feel_no_pain_decision,
    unit_by_id,
    unit_owner_player_id,
)
from warhammer40k_core.engine.damage_allocation_targets import (
    DamageAllocationTargetState,
    damage_allocation_target_state,
)
from warhammer40k_core.engine.decision_controller import DecisionController
from warhammer40k_core.engine.decision_request import DecisionOption, DecisionRequest
from warhammer40k_core.engine.decision_result import DecisionResult
from warhammer40k_core.engine.destruction_provenance import (
    DestructionAttackKind,
    DestructionProvenance,
    DestructionProvenancePayload,
    DestructionSourceKind,
)
from warhammer40k_core.engine.dice import DICE_REROLL_DECISION_TYPE, DiceRollManager
from warhammer40k_core.engine.event_log import (
    EventRecord,
    JsonValue,
    canonical_json,
    validate_json_value,
)
from warhammer40k_core.engine.fight_on_death import (
    restore_selected_model_awaiting_fight_on_death,
)
from warhammer40k_core.engine.hazard import (
    hazard_mortal_wounds_per_failed_roll,
    hazard_roll_failed,
    hazard_roll_spec,
)
from warhammer40k_core.engine.movement_proposals import (
    PLACEMENT_PROPOSAL_DECISION_TYPE,
    MovementProposalRequest,
    PlacementProposalPayload,
    PlacementProposalPayloadPayload,
    ProposalKind,
    ProposalValidationResult,
)
from warhammer40k_core.engine.opportunity_windows import (
    OPPORTUNITY_REQUEST_FAMILY,
    OPPORTUNITY_SUBMISSION_PAYLOAD_KEY,
    OpportunityActionKind,
    OpportunityLegalAction,
    OpportunityWindow,
    TriggerBatchingMode,
    opportunity_boundary_game_state_payload,
    opportunity_boundary_state_hash,
)
from warhammer40k_core.engine.phase import (
    BattlePhase,
    GameLifecycleError,
    GameLifecycleStage,
    LifecycleStatus,
)
from warhammer40k_core.engine.rules_units import rules_unit_view_by_id
from warhammer40k_core.engine.runtime_modifiers import (
    AttackRerollPermissionContext,
    DamageRollModifierContext,
    FailedSaveDamageReplacement,
    FailedSaveDamageReplacementContext,
    HitRollMinimumUnmodifiedSuccessContext,
    HitRollModifierContext,
    RuntimeModifierRegistry,
    SaveOptionModifierContext,
    UnitCharacteristicModifierContext,
    WoundRollModifierContext,
    unified_attack_reroll_permission_contexts_for_unit,
)
from warhammer40k_core.engine.saves import (
    SaveKind,
    SaveOption,
    SaveOptionPayload,
    SavingThrow,
    mandatory_save_option,
    resolve_saving_throw,
    save_options_for_model,
    saving_throw_roll_spec,
)
from warhammer40k_core.engine.shooting_targets import (
    BENEFIT_OF_COVER_RULE_ID,
    PLUNGING_FIRE_RULE_ID,
    shooting_dynamic_model_blockers,
    shooting_visibility_cache_key,
)
from warhammer40k_core.engine.source_backed_rerolls import (
    SourceBackedRerollPermissionContext,
    select_source_backed_reroll_permission_context,
    source_backed_reroll_permission_context_for_unit,
    source_backed_reroll_permission_contexts_for_unit,
)
from warhammer40k_core.engine.timing_windows import (
    TimingTriggerKind,
    TimingWindow,
    TimingWindowDescriptor,
)
from warhammer40k_core.engine.transports import (
    DestroyedTransportDisembark,
    DestroyedTransportDisembarkPayload,
    DisembarkModeKind,
    DisembarkSelection,
    TransportCargoState,
    TransportMovementStatus,
    apply_destroyed_transport_disembark_to_battlefield,
    apply_transport_hazard_mortal_wounds,
    resolve_destroyed_transport_disembark,
)
from warhammer40k_core.engine.unit_factory import UnitInstance
from warhammer40k_core.engine.weapon_abilities import (
    DEVASTATING_WOUNDS_RULE_ID,
    FIRE_OVERWATCH_RULE_ID,
    HAZARDOUS_RULE_ID,
    INDIRECT_FIRE_BENEFIT_OF_COVER_RULE_ID,
    INDIRECT_FIRE_NO_HIT_REROLLS_RULE_ID,
    INDIRECT_FIRE_STATIONARY_VISIBLE_RULE_ID,
    LANCE_RULE_ID,
    MELTA_RULE_ID,
    PRECISION_RULE_ID,
    SNAP_SHOOTING_RULE_ID,
    SUSTAINED_HITS_D3_VALUE,
    TWIN_LINKED_RULE_ID,
    DevastatingWoundsResolution,
    anti_keyword_critical_threshold,
    devastating_wounds_resolution,
    has_weapon_keyword,
    is_psychic_weapon_profile,
    lethal_hits_applies,
    melta_damage_bonus,
    sustained_hits_generated_hits,
    weapon_ability_value,
)
from warhammer40k_core.engine.weapon_declaration import RangedAttackPool, RangedAttackPoolPayload
from warhammer40k_core.geometry.measurement import (
    DistanceMeasurementContext,
    objective_marker_controls_model,
)
from warhammer40k_core.geometry.pose import Pose
from warhammer40k_core.geometry.terrain import TerrainFeatureDefinition, TerrainVolume
from warhammer40k_core.geometry.visibility import (
    BenefitOfCoverResult,
    CoverSourceReason,
    CoverSourceRecord,
    LineOfSightWitness,
    TerrainVisibilityContext,
    VisibilityBlockerKind,
)
from warhammer40k_core.geometry.volume import Model as GeometryModel

if TYPE_CHECKING:
    from warhammer40k_core.engine.game_state import GameState
    from warhammer40k_core.engine.stratagems import StratagemCatalogIndex

__all__ = (
    "AbilityKind",
    "AllocationGroup",
    "AllocationGroupPayload",
    "AllocationGroupRole",
    "AllocationOrderDecision",
    "AttackAllocation",
    "AttackAllocationConstraint",
    "AttackAllocationPayload",
    "AttackAllocationRuleContext",
    "AttackAllocationRuleContextPayload",
    "AttackRerollPermissionContext",
    "BENEFIT_OF_COVER_RULE_ID",
    "BattlePhase",
    "BattlefieldPlacementKind",
    "BattlefieldRemovalKind",
    "BattlefieldScenario",
    "BattlefieldTransitionBatch",
    "BenefitOfCoverResult",
    "Callable",
    "Characteristic",
    "CoverEffect",
    "CoverSourceReason",
    "CoverSourceRecord",
    "DEVASTATING_WOUNDS_RULE_ID",
    "DICE_REROLL_DECISION_TYPE",
    "DamageAllocationModelDecision",
    "DamageAllocationTargetState",
    "DamageApplication",
    "DamageApplicationPayload",
    "DamageKind",
    "AllocatedAttackDamageModifierContext",
    "DamageRollModifierContext",
    "FailedSaveDamageReplacement",
    "FailedSaveDamageReplacementContext",
    "DamageProfile",
    "DamageProfilePayload",
    "DecisionController",
    "DecisionOption",
    "DecisionRequest",
    "DecisionResult",
    "DestroyedTransportDisembark",
    "DestroyedTransportDisembarkPayload",
    "DestructionReactionDecision",
    "DestructionReactionKind",
    "DestructionReactionSource",
    "DestructionReactionSourcePayload",
    "DevastatingWoundsResolution",
    "DiceExpression",
    "DiceRollManager",
    "DiceRollResult",
    "DiceRollResultPayload",
    "DiceRollSpec",
    "DiceRollState",
    "DiceRollStatePayload",
    "DestructionAttackKind",
    "DestructionProvenance",
    "DestructionProvenancePayload",
    "DestructionSourceKind",
    "DisembarkModeKind",
    "DisembarkSelection",
    "DistanceMeasurementContext",
    "EventRecord",
    "FIRE_OVERWATCH_RULE_ID",
    "FeelNoPainAttackCondition",
    "FeelNoPainDecision",
    "FeelNoPainResolution",
    "FeelNoPainResolutionPayload",
    "FeelNoPainSource",
    "FeelNoPainSourcePayload",
    "GO_TO_GROUND_EFFECT_KIND",
    "GameLifecycleError",
    "GameLifecycleStage",
    "GeometryModel",
    "HAZARDOUS_RULE_ID",
    "HitRollMinimumUnmodifiedSuccessContext",
    "HitRollModifierContext",
    "INDIRECT_FIRE_BENEFIT_OF_COVER_RULE_ID",
    "INDIRECT_FIRE_NO_HIT_REROLLS_RULE_ID",
    "INDIRECT_FIRE_STATIONARY_VISIBLE_RULE_ID",
    "IdentifierValidator",
    "JsonValue",
    "LANCE_RULE_ID",
    "LifecycleStatus",
    "LineOfSightWitness",
    "LineOfSightPolicy",
    "MELTA_RULE_ID",
    "ModelRemovalRecord",
    "ModifierStack",
    "ModifierStackPayload",
    "MortalWoundApplication",
    "MortalWoundApplicationProgress",
    "MortalWoundRoutingResult",
    "MovementProposalRequest",
    "NotRequired",
    "OPPORTUNITY_REQUEST_FAMILY",
    "OPPORTUNITY_SUBMISSION_PAYLOAD_KEY",
    "ObjectiveMarker",
    "OpportunityActionKind",
    "OpportunityLegalAction",
    "OpportunityWindow",
    "PLACEMENT_PROPOSAL_DECISION_TYPE",
    "PLUNGING_FIRE_RULE_ID",
    "PRECISION_RULE_ID",
    "PlacementError",
    "PlacementProposalPayload",
    "PlacementProposalPayloadPayload",
    "Pose",
    "ProposalKind",
    "ProposalValidationResult",
    "RandomCharacteristicRoll",
    "RandomCharacteristicTiming",
    "RangeProfileKind",
    "RangedAttackPool",
    "RangedAttackPoolPayload",
    "RerollComponentSelectionPolicy",
    "RerollPermission",
    "RollModifier",
    "RollModifierPayload",
    "RulesetDescriptor",
    "RuntimeModifierRegistry",
    "SELECT_ALLOCATION_ORDER_DECISION_TYPE",
    "SELECT_DAMAGE_ALLOCATION_MODEL_DECISION_TYPE",
    "SELECT_DESTRUCTION_REACTION_DECISION_TYPE",
    "SELECT_FEEL_NO_PAIN_DECISION_TYPE",
    "SELECT_PRECISION_ALLOCATION_DECISION_TYPE",
    "SNAP_SHOOTING_RULE_ID",
    "SUSTAINED_HITS_D3_VALUE",
    "SaveKind",
    "SaveOption",
    "SaveOptionModifierContext",
    "SaveOptionPayload",
    "SavingThrow",
    "Self",
    "SourceBackedRerollPermissionContext",
    "StrEnum",
    "TWIN_LINKED_RULE_ID",
    "TYPE_CHECKING",
    "TerrainFeatureDefinition",
    "TerrainFeatureKind",
    "TerrainVolume",
    "TerrainVisibilityContext",
    "TimingTriggerKind",
    "TimingWindow",
    "TimingWindowDescriptor",
    "TransportCargoState",
    "TransportMovementStatus",
    "TriggerBatchingMode",
    "TypedDict",
    "UnitCharacteristicModifierContext",
    "UnitInstance",
    "UnitPlacement",
    "VisibilityBlockerKind",
    "WeaponKeyword",
    "WeaponProfile",
    "WeaponProfileError",
    "WoundRollModifierContext",
    "allocation_context_for_unit",
    "allocation_groups_for_context",
    "anti_keyword_critical_threshold",
    "apply_damage_to_model",
    "apply_destroyed_transport_disembark_to_battlefield",
    "apply_transport_hazard_mortal_wounds",
    "battle_phase_kind_from_token",
    "build_allocation_order_request",
    "build_damage_allocation_model_request",
    "build_destruction_reaction_request",
    "build_feel_no_pain_request",
    "canonical_json",
    "cast",
    "continue_mortal_wound_application",
    "damage_allocation_target_state",
    "damage_kind_from_token",
    "dataclass",
    "devastating_wounds_resolution",
    "geometry_model_for_placement",
    "has_weapon_keyword",
    "hazard_mortal_wounds_per_failed_roll",
    "hazard_roll_failed",
    "hazard_roll_spec",
    "is_mortal_wound_feel_no_pain_request",
    "is_psychic_weapon_profile",
    "legal_allocation_group_orders",
    "lethal_hits_applies",
    "mandatory_save_option",
    "melta_damage_bonus",
    "model_by_id",
    "objective_marker_controls_model",
    "opportunity_boundary_game_state_payload",
    "opportunity_boundary_state_hash",
    "remove_destroyed_model_from_battlefield",
    "replace",
    "resolve_destroyed_transport_disembark",
    "resolve_feel_no_pain_rolls",
    "resolve_mortal_wound_feel_no_pain_decision",
    "resolve_saving_throw",
    "restore_selected_model_awaiting_fight_on_death",
    "rules_unit_view_by_id",
    "save_options_for_model",
    "saving_throw_roll_spec",
    "sha256",
    "shooting_dynamic_model_blockers",
    "shooting_visibility_cache_key",
    "source_backed_reroll_permission_context_for_unit",
    "source_backed_reroll_permission_contexts_for_unit",
    "select_source_backed_reroll_permission_context",
    "sustained_hits_generated_hits",
    "unified_attack_reroll_permission_contexts_for_unit",
    "unit_by_id",
    "unit_effect_hit_roll_modifier",
    "unit_effect_invulnerable_save",
    "unit_effects_deny_benefit_of_cover",
    "unit_effects_grant_benefit_of_cover",
    "unit_owner_player_id",
    "validate_json_value",
    "weapon_ability_value",
)
