TARGET_CONSTRAINT_NOT_BELOW_HALF_STRENGTH = "target_not_below_half_strength"
TARGET_CONSTRAINT_TARGET_UNIT_BELOW_STARTING_STRENGTH = "target_unit_below_starting_strength"
TARGET_CONSTRAINT_TARGET_UNIT_BELOW_HALF_STRENGTH = "target_unit_below_half_strength"
TARGET_CONSTRAINT_SOURCE_UNIT_BELOW_STARTING_STRENGTH = "source_unit_below_starting_strength"
TARGET_CONSTRAINT_SOURCE_UNIT_BELOW_HALF_STRENGTH = "source_unit_below_half_strength"

__all__ = (
    "TARGET_CONSTRAINT_NOT_BELOW_HALF_STRENGTH",
    "TARGET_CONSTRAINT_SOURCE_UNIT_BELOW_HALF_STRENGTH",
    "TARGET_CONSTRAINT_SOURCE_UNIT_BELOW_STARTING_STRENGTH",
    "TARGET_CONSTRAINT_TARGET_UNIT_BELOW_HALF_STRENGTH",
    "TARGET_CONSTRAINT_TARGET_UNIT_BELOW_STARTING_STRENGTH",
)
