# Generated by tools/import_mfm_points.py.
# Regenerate with `uv run python tools/import_mfm_points.py`.
from __future__ import annotations

from importlib import import_module
from typing import Final, cast

from warhammer40k_core.rules.mfm_source import (
    MfmFactionRecord,
    MfmFactionRecordPayload,
    MfmSourceError,
    MfmSourcePackage,
    MfmSourcePackagePayload,
)

SOURCE_PACKAGE_ID: Final = "gw-11e-mfm-2026-06"
SOURCE_TITLE: Final = "Warhammer 40,000: Munitorum Field Manual"
SOURCE_VERSION: Final = "v1.0"
SOURCE_DATE: Final = "2026-06-17"
SOURCE_URL: Final = "https://mfm.warhammer-community.com/en/"
SOURCE_PAYLOAD_CHECKSUM_SHA256: Final = (
    "1e668fd51b4766516068b7ea9ea0fa79bc98680aa4e38f649caa17fa7400f2af"
)
EXCLUDED_FACTION_IDS: Final = ("chaos-titan-legions", "titan-legions")
_FACTION_MODULES: Final = {
    "adepta-sororitas": "adepta_sororitas",
    "adeptus-custodes": "adeptus_custodes",
    "adeptus-mechanicus": "adeptus_mechanicus",
    "aeldari": "aeldari",
    "astra-militarum": "astra_militarum",
    "black-templars": "black_templars",
    "blood-angels": "blood_angels",
    "chaos-daemons": "chaos_daemons",
    "chaos-knights": "chaos_knights",
    "chaos-space-marines": "chaos_space_marines",
    "dark-angels": "dark_angels",
    "death-guard": "death_guard",
    "deathwatch": "deathwatch",
    "drukhari": "drukhari",
    "emperors-children": "emperors_children",
    "genestealer-cults": "genestealer_cults",
    "grey-knights": "grey_knights",
    "imperial-agents": "imperial_agents",
    "imperial-knights": "imperial_knights",
    "leagues-of-votann": "leagues_of_votann",
    "necrons": "necrons",
    "orks": "orks",
    "space-marines": "space_marines",
    "space-wolves": "space_wolves",
    "tau-empire": "tau_empire",
    "thousand-sons": "thousand_sons",
    "tyranids": "tyranids",
    "world-eaters": "world_eaters",
}

_FACTION_CACHE: dict[str, MfmFactionRecord] = {}
_source_package_cache: MfmSourcePackage | None = None


def supported_faction_ids() -> tuple[str, ...]:
    return tuple(sorted(_FACTION_MODULES))


def faction_record(faction_id: str) -> MfmFactionRecord:
    cached = _FACTION_CACHE.get(faction_id)
    if cached is not None:
        return cached
    module_name = _FACTION_MODULES.get(faction_id)
    if module_name is None:
        raise MfmSourceError("MFM faction_id was not found in generated package.")
    module = import_module(f"{__name__}.{module_name}")
    payload = cast(MfmFactionRecordPayload, module.faction_payload())
    record = MfmFactionRecord.from_payload(payload)
    _FACTION_CACHE[faction_id] = record
    return record


def source_package() -> MfmSourcePackage:
    global _source_package_cache
    if _source_package_cache is None:
        _source_package_cache = MfmSourcePackage.from_payload(_source_package_payload())
    return _source_package_cache


def _source_package_payload() -> MfmSourcePackagePayload:
    return {
        "source_package_id": SOURCE_PACKAGE_ID,
        "source_title": SOURCE_TITLE,
        "source_version": SOURCE_VERSION,
        "source_date": SOURCE_DATE,
        "source_url": SOURCE_URL,
        "excluded_faction_ids": list(EXCLUDED_FACTION_IDS),
        "factions": [
            faction_record(faction_id).to_payload() for faction_id in supported_faction_ids()
        ],
        "source_payload_checksum_sha256": SOURCE_PAYLOAD_CHECKSUM_SHA256,
    }
