# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

from warhammer40k_core.engine.faction_content.bundle import RuntimeContentContribution

# Generated scaffold placeholder. Remove this marker when implementing semantics.

CONTRIBUTION_ID = "warhammer_40000_11th:drukhari:detachment:reapers_wager:rule:scaffold"


def runtime_contribution() -> RuntimeContentContribution:
    """Runtime load scaffold only.

    Semantic execution must be supplied by source-backed RuleIR,
    named handlers, event subscriptions, ability records, or Stratagem
    handler bindings in implementation PRs.
    """
    return RuntimeContentContribution(contribution_id=CONTRIBUTION_ID)
