# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

from warhammer40k_core.engine.faction_content.bundle import RuntimeContentContribution
from warhammer40k_core.rules.source_packages.warhammer_40000_11th import (
    faction_blood_legion_ir_support_2026_27 as blood_legion_ir,
)

CONTRIBUTION_ID = "warhammer_40000_11th:chaos_daemons:detachment:blood_legion:enhancements"
BRAZENMAW_ENHANCEMENT_ID = blood_legion_ir.BRAZENMAW_ENHANCEMENT_ID
BRAZENMAW_DESCRIPTOR_ID = blood_legion_ir.BRAZENMAW_DESCRIPTOR_ID
BRAZENMAW_SOURCE_RULE_ID = blood_legion_ir.BRAZENMAW_SOURCE_RULE_ID


def runtime_contribution() -> RuntimeContentContribution:
    """Expose the module while generic RuleIR owns Brazenmaw execution."""
    return RuntimeContentContribution(contribution_id=CONTRIBUTION_ID)
