# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

from warhammer40k_core.engine.faction_content.bundle import (
    RuntimeContentContribution,
    combine_runtime_content_contributions,
)

from .enhancements import runtime_contribution as enhancements_contribution
from .rule import runtime_contribution as rule_contribution
from .stratagems import runtime_contribution as stratagems_contribution

CONTRIBUTION_ID = "warhammer_40000_11th:dark_angels:detachment:company_of_hunters:manifest:scaffold"


def runtime_contribution() -> RuntimeContentContribution:
    return combine_runtime_content_contributions(
        contribution_id=CONTRIBUTION_ID,
        contributions=(
            rule_contribution(),
            enhancements_contribution(),
            stratagems_contribution(),
        ),
    )
