# ruff: noqa: F403,F405,I001
# pyright: reportUnknownVariableType=false
from __future__ import annotations

from warhammer40k_core.engine.phases import (
    movement_model as movement_model,
    movement_state as movement_state,
    movement_handler as movement_handler,
    movement_reactions as movement_reactions,
    movement_reinforcements as movement_reinforcements,
    movement_transports as movement_transports,
    movement_placement_proposals as movement_placement_proposals,
    movement_action_decisions as movement_action_decisions,
    movement_resolution_flow as movement_resolution_flow,
    movement_fall_back_embark as movement_fall_back_embark,
    movement_options_dice as movement_options_dice,
    movement_resolvers as movement_resolvers,
    movement_geometry as movement_geometry,
    movement_validation as movement_validation,
)
from warhammer40k_core.engine.phases.movement_bindings import bind_movement_modules
from warhammer40k_core.engine.phases.movement_model import *
from warhammer40k_core.engine.phases.movement_state import *
from warhammer40k_core.engine.phases.movement_handler import *
from warhammer40k_core.engine.phases.movement_reactions import *
from warhammer40k_core.engine.phases.movement_reinforcements import *
from warhammer40k_core.engine.phases.movement_transports import *
from warhammer40k_core.engine.phases.movement_placement_proposals import *
from warhammer40k_core.engine.phases.movement_action_decisions import *
from warhammer40k_core.engine.phases.movement_resolution_flow import *
from warhammer40k_core.engine.phases.movement_fall_back_embark import *
from warhammer40k_core.engine.phases.movement_options_dice import *
from warhammer40k_core.engine.phases.movement_resolvers import *
from warhammer40k_core.engine.phases.movement_geometry import *
from warhammer40k_core.engine.phases.movement_validation import *

bind_movement_modules()

__all__ = (
    "COMPLETE_DISEMBARKS_OPTION_ID",
    "COMPLETE_REINFORCEMENTS_OPTION_ID",
    "DECLINE_EMBARK_OPTION_ID",
    "SELECT_DESPERATE_ESCAPE_MODEL_DECISION_TYPE",
    "SELECT_DISEMBARK_UNIT_DECISION_TYPE",
    "SELECT_EMBARK_TRANSPORT_DECISION_TYPE",
    "SELECT_MOVEMENT_ACTION_DECISION_TYPE",
    "SELECT_MOVEMENT_UNIT_DECISION_TYPE",
    "SELECT_REINFORCEMENT_UNIT_DECISION_TYPE",
    "_ADVANCED_UNIT_CLEANUP_POINT",
    "_ADVANCE_REROLL_KEYWORD",
    "_DESPERATE_ESCAPE_ROLL_TYPE",
    "_FELL_BACK_UNIT_CLEANUP_POINT",
    "_MOVEMENT_ACTIONS_INSIDE_ENEMY_ENGAGEMENT",
    "_MOVEMENT_ACTIONS_OUTSIDE_ENEMY_ENGAGEMENT",
    "AdvanceMoveResolution",
    "AdvanceRollRequest",
    "AdvanceRollRequestPayload",
    "AdvanceRollResult",
    "AdvanceRollResultPayload",
    "AdvancedUnitState",
    "AdvancedUnitStatePayload",
    "DesperateEscapeRequirement",
    "DesperateEscapeRequirementPayload",
    "DesperateEscapeRequirementReason",
    "DesperateEscapeRoll",
    "DesperateEscapeRollPayload",
    "DisembarkCandidate",
    "FallBackActionResult",
    "FallBackActionResultPayload",
    "FallBackModeKind",
    "FellBackUnitState",
    "FellBackUnitStatePayload",
    "MovementActionAvailabilityContext",
    "MovementActionAvailabilityContextPayload",
    "MovementActionAvailabilityResult",
    "MovementActionAvailabilityResultPayload",
    "MovementDiceRecord",
    "MovementDiceRecordPayload",
    "MovementDistanceRecord",
    "MovementDistanceRecordPayload",
    "MovementPhaseActionKind",
    "MovementPhaseHandler",
    "MovementPhaseState",
    "MovementPhaseStatePayload",
    "MovementPhaseStepKind",
    "MovementUnitSelection",
    "MovementUnitSelectionPayload",
    "NormalMoveResolution",
    "PendingMovementActionSelection",
    "PendingMovementActionSelectionPayload",
    "_MovementProposalParseResult",
    "_PlacementProposalParseResult",
    "_ResolvedUnitMove",
    "_ability_index_for_player",
    "_action_result_from_proposal_request",
    "_active_movement_selection",
    "_active_player_end_movement_overwatch_trigger_unit_ids",
    "_active_player_id",
    "_advance_move_grant_option",
    "_advance_move_grants_from_context",
    "_advance_reroll_permission_for_unit",
    "_advance_roll_request_for_action",
    "_advance_roll_reroll_request",
    "_aircraft_reserve_transition_reason_for_normal_move",
    "_allowed_disembark_modes_for_placement_request",
    "_apply_advance_move_grant_decision",
    "_apply_advance_move_grants",
    "_apply_advance_roll_reroll_decision",
    "_apply_aircraft_reserve_transition_for_normal_move",
    "_apply_desperate_escape_model_selection_decision",
    "_apply_disembark_unit_selection_decision",
    "_apply_embark_transport_selection_decision",
    "_apply_fall_back_result",
    "_apply_movement_action_decision",
    "_apply_movement_proposal_decision",
    "_apply_placement_proposal_decision",
    "_apply_reinforcement_unit_selection_decision",
    "_apply_valid_combat_disembark",
    "_apply_valid_disembark",
    "_apply_valid_embark",
    "_apply_valid_reinforcement_placement",
    "_assert_advance_move_grant_still_available",
    "_battlefield_scenario",
    "_begin_reinforcements_step",
    "_canonical_keyword",
    "_complete_activation_then_request_post_normal_disembark_if_available",
    "_complete_movement_activation",
    "_complete_movement_activation_with_record_ids",
    "_complete_reinforcements_step",
    "_decision_payload_object",
    "_decline_advance_move_grant_option",
    "_deep_strike_enemy_distance_for_reserve_arrival",
    "_default_fall_back_witness",
    "_default_move_end_pose",
    "_default_move_witness",
    "_desperate_escape_model_selection_options",
    "_desperate_escape_model_selection_request",
    "_desperate_escape_requirements_for_fall_back",
    "_dice_roll_manager_for_state",
    "_disembark_unit_selection_options",
    "_effective_movement_keywords",
    "_eligible_reinforcement_reserve_states",
    "_eligible_triggered_movement_units_from_grants",
    "_empty_ability_indexes",
    "_enemy_engaged_unit_ids_for_unit_placement",
    "_enemy_engagement_model_ids_for_unit",
    "_enemy_geometry_models_for_player",
    "_enemy_model_ids_crossed_by_witness",
    "_enemy_vehicle_monster_model_ids_for_player",
    "_ensure_movement_phase_state",
    "_ensure_transport_cargo_phase_states",
    "_fall_back_mode_from_payload",
    "_fall_back_mode_from_proposal_submission",
    "_fall_back_mode_violation_code",
    "_fall_back_modes_for_parameterized_option",
    "_fall_back_result_with_mode",
    "_fall_back_transition_batch",
    "_fire_overwatch_end_movement_trigger_payload",
    "_forced_desperate_escape_source_rule_ids_from_context",
    "_forced_desperate_escape_sources_for_unit",
    "_friendly_geometry_models_for_path",
    "_friendly_unit_fell_back_context_from_event",
    "_friendly_unit_fell_back_timing_window_id",
    "_friendly_vehicle_monster_model_ids",
    "_geometry_models_for_unit_placement",
    "_grant_ranged_weapon_keywords",
    "_hover_mode_state_for_unit",
    "_identifier_list_from_json_object",
    "_interpolate_pose",
    "_interrupt_started_mission_actions_for_movement_activation",
    "_key_error_field",
    "_maximum_model_distance_inches_from_witness",
    "_missing_disembark_proposal_field",
    "_mission_action_state_is_active_for_unit",
    "_mission_setup_for_live_reinforcements",
    "_model_at_pose",
    "_model_base_movement_inches",
    "_model_default_movement_distance_inches",
    "_model_movement_budget_inches",
    "_model_movement_inches",
    "_modified_movement_inches",
    "_movement_action_availability_context",
    "_movement_action_availability_result",
    "_movement_action_grant_effect_expiration",
    "_movement_action_grant_unit_effect_target_ids",
    "_movement_action_invalid_payload",
    "_movement_action_label",
    "_movement_action_option_id",
    "_movement_action_options",
    "_movement_bonus_inches_for_unit",
    "_movement_completion_context_payload",
    "_movement_distance_modifier_inches",
    "_movement_end_surge_distance_roll_spec",
    "_movement_end_surge_event_already_processed",
    "_movement_end_surge_grant_distance_bonus",
    "_movement_mode_for_action",
    "_movement_mode_from_payload",
    "_movement_mode_from_proposal_submission",
    "_movement_modes_for_action_options",
    "_movement_transition_batch",
    "_movement_unit_options",
    "_normal_move_invalid_message",
    "_normal_move_transition_batch",
    "_normal_move_violation_code",
    "_objective_markers_for_state",
    "_optional_payload_path_witness",
    "_optional_proposal_context_string",
    "_overdue_required_reinforcement_reserve_states",
    "_parse_movement_proposal_submission_or_invalid",
    "_parse_placement_proposal_submission_or_invalid",
    "_path_result_with_aircraft_violations",
    "_payload_json_array",
    "_payload_json_object",
    "_payload_model_displacement_kind",
    "_payload_object",
    "_payload_positive_int",
    "_payload_string",
    "_payload_transition_batch",
    "_post_move_embark_options",
    "_post_normal_move_disembark_entries",
    "_pre_move_disembark_entries",
    "_proposal_payload_parse_failure",
    "_record_advance_roll_resolved_event",
    "_record_movement_action_grant_effects",
    "_reinforcement_unit_options",
    "_reject_invalid_movement_resolution",
    "_reject_invalid_proposal",
    "_remaining_move_units_unit_ids",
    "_request_advance_move_grant_decision_if_available",
    "_request_disembark_placement",
    "_request_embark_after_move_or_complete_activation",
    "_request_end_movement_active_player_stratagem_if_available",
    "_request_end_opponent_movement_reaction_if_available",
    "_request_fire_overwatch_reaction_if_available",
    "_request_friendly_unit_fell_back_stratagem_if_available",
    "_request_movement_action",
    "_request_movement_end_surge_if_available",
    "_request_movement_proposal",
    "_request_movement_proposal_retry",
    "_request_payload_for_result",
    "_request_pending_movement_action_proposal",
    "_request_placement_proposal_retry",
    "_request_post_normal_move_disembark_if_available",
    "_request_pre_move_disembark_if_available",
    "_request_rapid_ingress_reaction_if_available",
    "_request_reinforcement_placement",
    "_request_selected_to_fall_back_stratagem_if_available",
    "_request_selected_to_move_stratagem_if_available",
    "_required_reinforcement_reserve_states",
    "_reserve_placement_kinds_for_unit",
    "_reserve_proposal_kind",
    "_resolve_and_apply_advance_move",
    "_resolve_combat_disembark_placement_submission",
    "_resolve_disembark_placement_submission",
    "_resolve_pending_advance_action",
    "_resolve_pending_movement_action_after_grants",
    "_resolve_reinforcement_placement_submission",
    "_resolve_unit_move",
    "_roll_advance_dice",
    "_roll_desperate_escape_dice",
    "_ruleset_descriptor_for_handler",
    "_runtime_modifier_registry",
    "_sampled_witness_transit_poses",
    "_selected_advance_move_grant_hook_ids_from_context",
    "_selected_to_fall_back_timing_window_id",
    "_selected_to_fall_back_trigger_payload",
    "_selected_to_move_timing_window_id",
    "_stratagem_target_proposal_payload_factory",
    "_stratagem_use_payload_factory",
    "_stratagem_used_for_context",
    "_temporary_movement_keywords_for_unit",
    "_transport_operation_invalid_payload",
    "_transport_status_for_movement_action",
    "_unit_can_take_to_the_skies",
    "_unit_for_reserve_state",
    "_unit_has_deep_strike_keyword",
    "_unit_has_keyword",
    "_unit_has_vehicle_or_monster_keyword",
    "_unit_instance_by_id",
    "_validate_ability_index_mapping",
    "_validate_advance_roll_spec",
    "_validate_bool",
    "_validate_desperate_escape_reason_tuple",
    "_validate_desperate_escape_requirement_tuple",
    "_validate_desperate_escape_roll_tuple",
    "_validate_identifier",
    "_validate_identifier_tuple",
    "_validate_json_object",
    "_validate_move_witness_matches_unit",
    "_validate_movement_action_tuple",
    "_validate_movement_distance_records",
    "_validate_movement_phase_state",
    "_validate_non_negative_finite_number",
    "_validate_objective_marker_tuple",
    "_validate_path_validation_result_tuple",
    "_validate_positive_int",
    "_validate_terrain_path_legality_result_tuple",
    "_validate_transport_restriction_override_tuple",
    "assert_move_units_step_complete_for_reinforcements",
    "desperate_escape_requirement_reason_from_token",
    "fall_back_mode_kind_from_token",
    "movement_mode_for_phase_action",
    "movement_phase_action_kind_from_token",
    "movement_phase_step_kind_from_token",
    "resolve_advance_move",
    "resolve_fall_back_move",
    "resolve_normal_move",
)
