# ruff: noqa: F403,F405,I001
# pyright: reportUnknownVariableType=false
from __future__ import annotations

from warhammer40k_core.engine.phases import (
    shooting_model as shooting_model,
    shooting_handler as shooting_handler,
    shooting_reactions as shooting_reactions,
    shooting_requests as shooting_requests,
    shooting_unit_selection as shooting_unit_selection,
    shooting_decisions as shooting_decisions,
    shooting_declaration_validation as shooting_declaration_validation,
    shooting_targeting as shooting_targeting,
    shooting_firing_deck as shooting_firing_deck,
    shooting_eligibility as shooting_eligibility,
    shooting_validation as shooting_validation,
)
from warhammer40k_core.engine.phases.shooting_bindings import bind_shooting_modules
from warhammer40k_core.engine.phases.shooting_model import *
from warhammer40k_core.engine.phases.shooting_handler import *
from warhammer40k_core.engine.phases.shooting_reactions import *
from warhammer40k_core.engine.phases.shooting_requests import *
from warhammer40k_core.engine.phases.shooting_unit_selection import *
from warhammer40k_core.engine.phases.shooting_decisions import *
from warhammer40k_core.engine.phases.shooting_declaration_validation import *
from warhammer40k_core.engine.phases.shooting_targeting import *
from warhammer40k_core.engine.phases.shooting_firing_deck import *
from warhammer40k_core.engine.phases.shooting_eligibility import *
from warhammer40k_core.engine.phases.shooting_validation import *

bind_shooting_modules()

__all__ = (
    "COMPLETE_SHOOTING_PHASE_OPTION_ID",
    "SELECT_SHOOTING_TYPE_DECISION_TYPE",
    "SELECT_SHOOTING_UNIT_DECISION_TYPE",
    "SUBMIT_SHOOTING_DECLARATION_DECISION_TYPE",
    "_COMPLETE_SHOOTING_PHASE_STATUS",
    "OutOfPhaseShootingState",
    "OutOfPhaseShootingStatePayload",
    "ShootingDeclarationDecisionPayload",
    "ShootingDeclarationProposalRequestPayload",
    "ShootingPhaseHandler",
    "ShootingPhaseState",
    "ShootingPhaseStatePayload",
    "ShootingTypeSelection",
    "ShootingTypeSelectionPayload",
    "ShootingUnitSelection",
    "ShootingUnitSelectionPayload",
    "_AttackPoolValidationResult",
    "_AvailableWeapon",
    "_ShootingModelCandidateCache",
    "_ShootingModelCandidateCacheKey",
    "_ShootingUnitCandidateCacheKey",
    "_active_player_id",
    "_active_player_placed_unit_ids",
    "_active_shooting_phase_stratagem_timing_window_id",
    "_active_shooting_unit_selection",
    "_advanced_unit_is_restricted_to_assault_weapons",
    "_apply_attack_sequence_decision",
    "_apply_attack_sequence_decision_to_sequence",
    "_apply_attack_sequence_selection_decision",
    "_apply_attack_sequence_selection_to_sequence",
    "_apply_out_of_phase_shooting_declaration_decision",
    "_apply_phase13d_weapon_modifiers",
    "_apply_shooting_declaration_decision",
    "_apply_shooting_dice_reroll_decision",
    "_apply_shooting_type_selection_decision",
    "_apply_shooting_unit_selected_effect_grants",
    "_apply_shooting_unit_selected_grant_decision",
    "_apply_shooting_unit_selection_decision",
    "_army_catalog_for_handler",
    "_attack_pools_for_proposal",
    "_attack_pools_or_validation",
    "_attack_sequence_completed_event_id",
    "_attack_sequence_for_selection_request",
    "_available_firing_deck_weapons",
    "_available_own_weapons_for_model",
    "_available_weapon_by_declaration_key_for_rules_unit",
    "_available_weapon_key",
    "_available_weapon_to_payload",
    "_available_weapons_for_model",
    "_available_weapons_for_rules_unit",
    "_available_weapons_for_unit",
    "_battlefield_scenario",
    "_cached_shooting_target_candidate_for_model",
    "_canonical_keyword",
    "_complete_out_of_phase_shooting",
    "_component_unit_by_id",
    "_component_unit_for_available_weapon",
    "_component_unit_for_declaration",
    "_decision_payload_object",
    "_declaration_available_weapon_key",
    "_declaration_source_model_id",
    "_declaration_source_unit",
    "_declaration_target_within_max_range",
    "_default_stratagem_index",
    "_destroyed_enemy_unit_ids_for_sequence",
    "_destroyed_target_unit_ids_for_sequence",
    "_detection_range_bonus_inches_by_target_id",
    "_eligible_triggered_movement_units_from_shooting_grants",
    "_embedded_weapon_ability_request_prefix",
    "_enemy_placed_unit_ids",
    "_enemy_unit_has_shot_timing_window_id",
    "_ensure_shooting_phase_state",
    "_firing_deck_value_for_rules_unit",
    "_firing_deck_value_for_unit",
    "_forced_shooting_type_for_out_of_phase",
    "_friendly_unit_has_shot_timing_window_id",
    "_heavy_hit_roll_modifier_applies",
    "_hidden_target_unit_ids",
    "_invalid_finite_decision_status",
    "_invalid_if_current_option_payload_drifted",
    "_legal_shooting_types_for_rules_unit",
    "_legal_shooting_unit_ids",
    "_model_by_id",
    "_model_has_wargear_id",
    "_modified_shooting_weapon_profile",
    "_out_of_phase_allowed_target_unit_ids",
    "_out_of_phase_uses_fire_overwatch",
    "_payload_int",
    "_payload_string",
    "_proposal_request_from_decision_request",
    "_record_one_shot_weapon_uses_for_attack_pools",
    "_record_ranged_attack_history_for_declaration",
    "_record_shooting_unit_selected_grant_effects",
    "_reject_invalid_declaration",
    "_request_active_shooting_phase_stratagem_if_available",
    "_request_after_unit_selected_as_target_stratagem_if_available",
    "_request_enemy_unit_has_shot_stratagem_if_available",
    "_request_friendly_unit_has_shot_stratagem_if_available",
    "_request_shooting_declaration",
    "_request_shooting_end_surge_if_available",
    "_request_shooting_phase_start_rule_if_available",
    "_request_shooting_type_selection",
    "_request_shooting_unit_selected_grant_decision_if_available",
    "_required_weapon_ability_selections_for_target",
    "_resolve_completed_shooting_attack_sequence_continuation",
    "_rules_unit_advanced_is_restricted_to_assault_weapons",
    "_rules_unit_advanced_this_turn",
    "_rules_unit_can_select_to_shoot",
    "_rules_unit_has_assault_ranged_weapon",
    "_rules_unit_has_indirect_ranged_weapon",
    "_rules_unit_has_legal_shooting_declaration",
    "_rules_unit_has_vehicle_or_monster_keyword",
    "_rules_unit_label",
    "_rules_unit_remained_stationary",
    "_rules_unit_set_up_this_turn",
    "_rules_unit_state_unit_ids",
    "_rules_unit_within_enemy_engagement_range",
    "_ruleset_descriptor_for_handler",
    "_runtime_modifier_registry",
    "_selected_as_target_timing_window_id",
    "_selected_shooting_type_for_declaration",
    "_selected_shooting_unit_grants_from_payload",
    "_shooting_candidate_with_target_restrictions",
    "_shooting_end_surge_distance_roll_spec",
    "_shooting_end_surge_event_already_processed",
    "_shooting_end_surge_grant_distance_bonus",
    "_shooting_model_candidate_cache_key",
    "_shooting_phase_start_faction_rule_drift_reason",
    "_shooting_phase_status_payload",
    "_shooting_type_options",
    "_shooting_types_for_candidate_payload",
    "_shooting_types_for_declaration_candidate",
    "_shooting_types_for_selected_type",
    "_shooting_types_for_selected_type_for_rules_unit",
    "_shooting_unit_candidate_cache_key",
    "_shooting_unit_options",
    "_shooting_unit_selected_context",
    "_shooting_unit_selected_grant_effect_expiration",
    "_shooting_unit_selected_grant_options",
    "_shooting_unit_selected_grant_unit_effect_target_ids",
    "_shot_source_unit_ids_for_detection_effects",
    "_snap_shooting_type_allowed_for_unit_target",
    "_stratagem_used_for_context",
    "_successful_hit_target_unit_ids_for_sequence",
    "_target_candidate_payload_for_request",
    "_target_unit_ids_for_attack_sequence",
    "_target_unit_ids_with_recent_ranged_attacks",
    "_target_visible_to_friendly_unit",
    "_target_within_half_weapon_range",
    "_targeting_detection_context_fingerprint",
    "_targeting_rule_ids_with_shooting_type",
    "_terrain_features_for_state",
    "_transport_firing_deck_model",
    "_unit_advanced_this_turn",
    "_unit_by_id",
    "_unit_can_select_to_shoot",
    "_unit_has_already_shot",
    "_unit_has_assault_ranged_weapon",
    "_unit_has_indirect_ranged_weapon",
    "_unit_has_keyword",
    "_unit_has_legal_shooting_declaration",
    "_unit_has_vehicle_or_monster_keyword",
    "_unit_placements_for_rules_unit_or_none",
    "_unit_target_within_max_range",
    "_validate_attack_pools",
    "_validate_declaration_submission",
    "_validate_duplicate_weapon_ability_selection",
    "_validate_firing_deck_selection",
    "_validate_firing_deck_weapon_against_catalog",
    "_validate_identifier",
    "_validate_identifier_tuple",
    "_validate_model_pistol_exclusivity",
    "_validate_out_of_phase_declaration_submission",
    "_validate_positive_int",
    "_validate_selected_shooting_unit_grants",
    "_validate_shooting_phase_state",
    "_validate_shooting_unit_selected_grant_payload_context",
    "_wargear_by_id",
    "_weapon_profile_cache_fingerprint",
    "_weapon_profile_for_wargear",
    "apply_hidden_status_loss_after_ranged_attacks",
    "invalid_shooting_phase_start_faction_rule_status",
    "request_out_of_phase_shooting_declaration",
    "shooting_rules_unit_has_legal_declaration_against_targets",
    "shooting_rules_unit_is_eligible_to_shoot",
    "shooting_unit_can_select_to_shoot",
    "shooting_unit_has_legal_declaration_against_targets",
)
