from __future__ import annotations

import hashlib
import json
import math
from collections import Counter
from collections.abc import Callable

import msgspec

from warhammer40k_core.rules.source_packages.warhammer_40000_11th.event_companion_layouts_2026_06.event_companion_full_artifact_errors import (  # noqa: E501
    EventCompanionBattlefieldArtifactError,
)
from warhammer40k_core.rules.source_packages.warhammer_40000_11th.event_companion_layouts_2026_06.event_companion_full_artifact_geometry_validation import (  # noqa: E501
    validate_area_contacts,
    validate_area_pose_witness,
    validate_area_runtime_orientation,
    validate_artifact_polygon,
    validate_centered_archetype_polygon,
    validate_component_capacities,
    validate_component_contact_semantics,
    validate_component_mirror_links,
    validate_component_pose_witness,
    validate_component_runtime_pose,
    validate_contact_pairs,
    validate_territory_geometry,
)
from warhammer40k_core.rules.source_packages.warhammer_40000_11th.event_companion_layouts_2026_06.event_companion_full_artifact_types import (  # noqa: E501
    ARTIFACT_SCHEMA,
    BattlefieldLayoutArtifact,
    EventCompanionBattlefieldArtifact,
    PdfAffineArtifact,
    PdfBoundsArtifact,
    SourceCoordinateFrameArtifact,
    SourceImageAssetArtifact,
    TerrainAreaArtifact,
    TerrainComponentPlacementArtifact,
    TerrainFeatureArchetypeArtifact,
)

SOURCE_PACKAGE_ID = "gw-11e-warhammer-event-companion-v1-1-2026-07"
SOURCE_PDF_FILENAME = "eng_22-07_warhammer40000_event_companion-alyapl19us-b2drgwkji4.pdf"
SOURCE_PDF_SHA256 = "97ae5591be2e58bdb636e97127eac0877f9bf28b29fc607ed4ead4d377fb8f20"
SOURCE_PAGES = tuple(range(8, 54))
LAYOUT_SOURCE_PAGES = tuple(range(9, 54))
SOURCE_BACKGROUND_IMAGE_XREF = 5490
SOURCE_BACKGROUND_IMAGE_SHA256 = "2eda9e45dadd328907dba59ca1f6630e816571e2bcfc20b1f5bf97f0c8b8772a"
SOURCE_BACKGROUND_BOUNDS_POINTS = (127.690826, 276.662323, 468.448334, 741.498596)
BATTLEFIELD_WIDTH_INCHES = 44.0
BATTLEFIELD_DEPTH_INCHES = 60.0
TERRAIN_PLACEMENT_INCREMENT_INCHES = 0.05

# The byte loader rejects any generated bytes or canonical package content that
# differs from these independently reviewed pins.
EXPECTED_SOURCE_EXTRACTION_PAYLOAD_SHA256 = (
    "a3e9392adeb52696902a016e3c3529933d1e99f3bfd67069d607410d8e1c137f"
)
EXPECTED_PACKAGE_HASH = "44ed73534435ab9fc10062024ecb92222898f8aeb0bdf54bd434582a58357972"
EXPECTED_ARTIFACT_SHA256 = "028670e0b1d965b7be90a95ba76f6bc74e7e26d3d1fd93b3dbf9e76e105d9b7f"
_PENDING_REVIEWED_PIN_PREFIX = "PENDING_REVIEWED_"

_LAYOUT_FAMILIES = (
    (
        "take-and-hold",
        "take-and-hold",
        9,
        ("primary-battlefield-dominance", "primary-battlefield-dominance"),
        (1, 2, 3),
    ),
    (
        "take-and-hold",
        "purge-the-foe",
        12,
        ("primary-immovable-object", "primary-unstoppable-force"),
        (4, 3, 5),
    ),
    (
        "take-and-hold",
        "disruption",
        15,
        ("primary-determined-acquisition", "primary-death-trap"),
        (4, 6, 5),
    ),
    (
        "take-and-hold",
        "reconnaissance",
        18,
        ("primary-purge-and-secure", "primary-reconnaissance-sweep"),
        (1, 2, 3),
    ),
    (
        "take-and-hold",
        "priority-assets",
        21,
        ("primary-inescapable-dominion", "primary-secure-asset"),
        (6, 5, 2),
    ),
    (
        "purge-the-foe",
        "purge-the-foe",
        24,
        ("primary-meatgrinder", "primary-meatgrinder"),
        (3, 1, 4),
    ),
    (
        "purge-the-foe",
        "disruption",
        27,
        ("primary-punishment", "primary-delaying-action"),
        (3, 1, 4),
    ),
    (
        "purge-the-foe",
        "reconnaissance",
        30,
        ("primary-consecrate", "primary-triangulation"),
        (5, 2, 6),
    ),
    (
        "purge-the-foe",
        "priority-assets",
        33,
        ("primary-destroyers-wrath", "primary-vital-link"),
        (2, 3, 5),
    ),
    (
        "disruption",
        "disruption",
        36,
        ("primary-outmaneuver", "primary-outmaneuver"),
        (6, 1, 4),
    ),
    (
        "disruption",
        "reconnaissance",
        39,
        ("primary-smoke-and-mirrors", "primary-surveil-the-foe"),
        (1, 2, 3),
    ),
    (
        "disruption",
        "priority-assets",
        42,
        ("primary-locate-and-deny", "primary-extract-relic"),
        (4, 1, 3),
    ),
    (
        "reconnaissance",
        "reconnaissance",
        45,
        ("primary-gather-intel", "primary-gather-intel"),
        (4, 6, 1),
    ),
    (
        "reconnaissance",
        "priority-assets",
        48,
        ("primary-search-and-scour", "primary-vanguard-operation"),
        (6, 1, 4),
    ),
    (
        "priority-assets",
        "priority-assets",
        51,
        ("primary-sabotage", "primary-sabotage"),
        (4, 6, 1),
    ),
)

EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER = tuple(
    f"{left_id}-vs-{right_id}-layout-{layout_number}"
    for left_id, right_id, _page, _missions, _templates in _LAYOUT_FAMILIES
    for layout_number in (1, 2, 3)
)
EXPECTED_LAYOUT_IDS = frozenset(EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER)
EXPECTED_LAYOUT_ID_BY_PAGE = dict(
    zip(LAYOUT_SOURCE_PAGES, EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER, strict=True)
)
EXPECTED_FORCE_DISPOSITION_PAIR_BY_LAYOUT = {
    f"{left_id}-vs-{right_id}-layout-{layout_number}": (left_id, right_id)
    for left_id, right_id, _page, _missions, _templates in _LAYOUT_FAMILIES
    for layout_number in (1, 2, 3)
}
EXPECTED_PRIMARY_MISSIONS_BY_LAYOUT = {
    f"{left_id}-vs-{right_id}-layout-{layout_number}": missions
    for left_id, right_id, _page, missions, _templates in _LAYOUT_FAMILIES
    for layout_number in (1, 2, 3)
}
EXPECTED_DEPLOYMENT_TEMPLATE_BY_LAYOUT = {
    f"{left_id}-vs-{right_id}-layout-{layout_number}": templates[layout_number - 1]
    for left_id, right_id, _page, _missions, templates in _LAYOUT_FAMILIES
    for layout_number in (1, 2, 3)
}

EXPECTED_TERRAIN_AREA_FAMILY_COUNTS = Counter(
    {
        "FOOTPRINT_6X4": 4,
        "FOOTPRINT_10X2_5": 2,
        "FOOTPRINT_6X2": 4,
        "FOOTPRINT_7X11_5": 4,
        "FOOTPRINT_8X11_5_POLYGON": 2,
    }
)
_EXPECTED_VECTOR_ITEM_COUNT_BY_FOOTPRINT = {
    "FOOTPRINT_6X4": 29,
    "FOOTPRINT_10X2_5": 33,
    "FOOTPRINT_6X2": 23,
    "FOOTPRINT_7X11_5": 40,
    "FOOTPRINT_8X11_5_POLYGON": 67,
}
EXPECTED_COMPONENT_ARCHETYPE_COUNTS = Counter(
    {
        "dense-downed-hovercraft": 2,
        "light-long-barricade": 2,
        "dense-industrial-crates": 2,
        "light-end-barricade": 4,
        "ruins-cd": 2,
        "ruins-gh": 2,
        "ruins-ef": 2,
        "ruins-ab": 2,
        "light-corner-ab": 2,
        "light-corner-cd": 2,
        "light-corner-ef": 2,
        "light-corner-gh": 2,
        "dense-tall-crates": 2,
        "dense-long-pipes": 2,
    }
)
_PAGE_9_COMPONENT_ARCHETYPE_COUNTS = EXPECTED_COMPONENT_ARCHETYPE_COUNTS.copy()
_PAGE_9_COMPONENT_ARCHETYPE_COUNTS["dense-tall-crates"] = 1
EXPECTED_COMPONENT_ARCHETYPE_COUNTS_BY_LAYOUT = {
    layout_id: (
        _PAGE_9_COMPONENT_ARCHETYPE_COUNTS
        if layout_id == "take-and-hold-vs-take-and-hold-layout-1"
        else EXPECTED_COMPONENT_ARCHETYPE_COUNTS
    )
    for layout_id in EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER
}
EXPECTED_COMPONENT_COUNT_BY_LAYOUT = {
    layout_id: sum(counts.values())
    for layout_id, counts in EXPECTED_COMPONENT_ARCHETYPE_COUNTS_BY_LAYOUT.items()
}
EXPECTED_TOTAL_COMPONENT_COUNT = sum(EXPECTED_COMPONENT_COUNT_BY_LAYOUT.values())
EXPECTED_COMPONENT_CONTACT_COUNT_BY_LAYOUT = {
    layout_id: (5 if layout_id == "take-and-hold-vs-take-and-hold-layout-1" else 6)
    for layout_id in EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER
}
_EXPECTED_AREA_CONTACT_COUNT_BY_PAGE = {
    9: 7,
    10: 7,
    11: 3,
    12: 6,
    13: 4,
    14: 4,
    15: 5,
    16: 5,
    17: 5,
    18: 7,
    19: 5,
    20: 5,
    21: 4,
    22: 4,
    23: 6,
    24: 4,
    25: 4,
    26: 4,
    27: 4,
    28: 4,
    29: 4,
    30: 4,
    31: 6,
    32: 4,
    33: 4,
    34: 4,
    35: 4,
    36: 7,
    37: 5,
    38: 7,
    39: 6,
    40: 4,
    41: 6,
    42: 3,
    43: 5,
    44: 5,
    45: 7,
    46: 7,
    47: 5,
    48: 7,
    49: 5,
    50: 7,
    51: 3,
    52: 3,
    53: 5,
}
_EXPECTED_OBJECTIVE_ROLE_COUNTS_BY_PAGE = {
    page: Counter(
        {
            "attacker_home": 1,
            "defender_home": 1,
            "central": (2 if page in {*range(12, 15), *range(21, 36), *range(39, 42)} else 1),
            "expansion": 2,
        }
    )
    for page in LAYOUT_SOURCE_PAGES
}
_EXPECTED_UNBOUND_OBJECTIVE_IDS = {
    "disruption-vs-priority-assets-layout-3-central-01",
    "priority-assets-vs-priority-assets-layout-1-central-01",
    "priority-assets-vs-priority-assets-layout-3-central-01",
}
_MEATGRINDER_LAYOUT_IDS = {
    f"purge-the-foe-vs-purge-the-foe-layout-{layout_number}" for layout_number in range(1, 4)
}
_EXPECTED_SOURCE_LAYOUT_ID_OVERRIDES = {
    "take-and-hold-vs-take-and-hold-layout-1": (
        "gw_event_companion_v1_take_and_hold_vs_take_and_hold_battlefield_dominance_layout_a"
    ),
    "take-and-hold-vs-take-and-hold-layout-2": (
        "gw_event_companion_v1_take_and_hold_vs_take_and_hold_battlefield_dominance_layout_b"
    ),
    "take-and-hold-vs-take-and-hold-layout-3": (
        "gw_event_companion_v1_take_and_hold_vs_take_and_hold_battlefield_dominance_layout_c"
    ),
    "purge-the-foe-vs-purge-the-foe-layout-1": (
        "gw_event_companion_v1_purge_the_foe_vs_purge_the_foe_meatgrinder_layout_a"
    ),
    "purge-the-foe-vs-purge-the-foe-layout-2": (
        "gw_event_companion_v1_purge_the_foe_vs_purge_the_foe_meatgrinder_layout_b"
    ),
    "purge-the-foe-vs-purge-the-foe-layout-3": (
        "gw_event_companion_v1_purge_the_foe_vs_purge_the_foe_meatgrinder_layout_c"
    ),
    "disruption-vs-reconnaissance-layout-1": (
        "gw_event_companion_v1_disruption_vs_reconnaissance_smoke_and_mirrors_"
        "surveil_the_foe_layout_a"
    ),
    "disruption-vs-reconnaissance-layout-2": (
        "gw_event_companion_v1_disruption_vs_reconnaissance_smoke_and_mirrors_"
        "surveil_the_foe_layout_b"
    ),
    "disruption-vs-reconnaissance-layout-3": (
        "gw_event_companion_v1_disruption_vs_reconnaissance_smoke_and_mirrors_"
        "surveil_the_foe_layout_c"
    ),
}
EXPECTED_ARCHETYPE_MODEL_KIND_COUNTS = Counter({"ruin": 4, "dense_solid": 4, "light_solid": 6})
EXPECTED_COMPONENT_MODEL_KIND_COUNTS = Counter({"ruin": 8, "dense_solid": 8, "light_solid": 14})
_PAGE_9_COMPONENT_MODEL_KIND_COUNTS = EXPECTED_COMPONENT_MODEL_KIND_COUNTS.copy()
_PAGE_9_COMPONENT_MODEL_KIND_COUNTS["dense_solid"] = 7
EXPECTED_COMPONENT_MODEL_KIND_COUNTS_BY_LAYOUT = {
    layout_id: (
        _PAGE_9_COMPONENT_MODEL_KIND_COUNTS
        if layout_id == "take-and-hold-vs-take-and-hold-layout-1"
        else EXPECTED_COMPONENT_MODEL_KIND_COUNTS
    )
    for layout_id in EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER
}

# Values are: source xrefs, model kind, feature kind, classification,
# optional source label, and terrain-area footprint family.
EXPECTED_ARCHETYPE_SEMANTICS = {
    "dense-downed-hovercraft": (
        (5462,),
        "dense_solid",
        "battlefield_debris_and_statuary",
        "dense",
        None,
        "FOOTPRINT_6X4",
    ),
    "light-long-barricade": (
        (5464,),
        "light_solid",
        "battlefield_debris_and_statuary",
        "light",
        None,
        "FOOTPRINT_6X2",
    ),
    "dense-industrial-crates": (
        (5466,),
        "dense_solid",
        "battlefield_debris_and_statuary",
        "dense",
        None,
        "FOOTPRINT_10X2_5",
    ),
    "light-end-barricade": (
        (5468,),
        "light_solid",
        "battlefield_debris_and_statuary",
        "light",
        None,
        "FOOTPRINT_10X2_5",
    ),
    "ruins-cd": ((5470,), "ruin", "ruins", "dense", "CD", "FOOTPRINT_7X11_5"),
    "ruins-gh": ((5472,), "ruin", "ruins", "dense", "GH", "FOOTPRINT_7X11_5"),
    "ruins-ef": ((5474,), "ruin", "ruins", "dense", "EF", "FOOTPRINT_7X11_5"),
    "ruins-ab": (
        (5476,),
        "ruin",
        "ruins",
        "dense",
        "AB",
        "FOOTPRINT_8X11_5_POLYGON",
    ),
    "light-corner-ab": (
        (5478,),
        "light_solid",
        "battlefield_debris_and_statuary",
        "light",
        None,
        "FOOTPRINT_8X11_5_POLYGON",
    ),
    "light-corner-cd": (
        (5480, 2889),
        "light_solid",
        "battlefield_debris_and_statuary",
        "light",
        None,
        "FOOTPRINT_6X4",
    ),
    "light-corner-ef": (
        (5482,),
        "light_solid",
        "battlefield_debris_and_statuary",
        "light",
        None,
        "FOOTPRINT_7X11_5",
    ),
    "light-corner-gh": (
        (5484, 2887),
        "light_solid",
        "battlefield_debris_and_statuary",
        "light",
        None,
        "FOOTPRINT_6X4",
    ),
    "dense-tall-crates": (
        (
            5486,
            5675,
            5519,
            5558,
            5678,
            5680,
            1014,
            1556,
            2073,
            3151,
            3153,
            3415,
            3417,
            3835,
            3968,
            4648,
            4900,
        ),
        "dense_solid",
        "battlefield_debris_and_statuary",
        "dense",
        None,
        "FOOTPRINT_6X4",
    ),
    "dense-long-pipes": (
        (5488, 2885, 3279),
        "dense_solid",
        "battlefield_debris_and_statuary",
        "dense",
        None,
        "FOOTPRINT_6X2",
    ),
}


def event_companion_battlefield_artifact_from_json_bytes(
    raw: bytes,
) -> EventCompanionBattlefieldArtifact:
    try:
        artifact = msgspec.json.decode(raw, type=EventCompanionBattlefieldArtifact)
    except msgspec.DecodeError as exc:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield artifact is invalid."
        ) from exc
    validate_event_companion_battlefield_artifact(artifact)
    expected_artifact_hash = _require_reviewed_pin(
        "artifact byte SHA-256",
        EXPECTED_ARTIFACT_SHA256,
    )
    _require_reviewed_pin(
        "source extraction payload SHA-256",
        EXPECTED_SOURCE_EXTRACTION_PAYLOAD_SHA256,
    )
    _require_reviewed_pin("package SHA-256", EXPECTED_PACKAGE_HASH)
    if hashlib.sha256(raw).hexdigest() != expected_artifact_hash:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield artifact bytes drifted from their reviewed pin."
        )
    return artifact


def validate_event_companion_battlefield_artifact(
    artifact: EventCompanionBattlefieldArtifact,
) -> None:
    if artifact.artifact_schema != ARTIFACT_SCHEMA:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield artifact schema is unsupported."
        )
    if (
        artifact.source_package_id,
        artifact.source_pdf_filename,
        artifact.source_pdf_sha256,
        artifact.source_pages,
    ) != (
        SOURCE_PACKAGE_ID,
        SOURCE_PDF_FILENAME,
        SOURCE_PDF_SHA256,
        SOURCE_PAGES,
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield source provenance drifted."
        )
    _validate_sha256(
        "source extraction payload SHA-256",
        artifact.source_extraction_payload_sha256,
    )
    if _reviewed_pin_is_configured(EXPECTED_SOURCE_EXTRACTION_PAYLOAD_SHA256) and (
        artifact.source_extraction_payload_sha256 != EXPECTED_SOURCE_EXTRACTION_PAYLOAD_SHA256
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield extraction payload drifted from its reviewed pin."
        )
    _validate_source_coordinate_frame(artifact.source_coordinate_frame)
    archetypes_by_id = _validate_archetypes(artifact.feature_archetypes)
    layouts_by_id = _unique_by_id("layout", artifact.layouts, lambda layout: layout.layout_id)
    if tuple(layouts_by_id) != EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield layouts must contain all 45 canonical IDs in page order."
        )
    source_layout_ids = _unique_by_id(
        "source layout",
        artifact.layouts,
        lambda layout: layout.source_layout_id,
    )
    if len(source_layout_ids) != len(EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source layout inventory drifted."
        )
    for source_page, layout in zip(LAYOUT_SOURCE_PAGES, artifact.layouts, strict=True):
        _validate_layout(
            layout,
            expected_source_page=source_page,
            archetypes_by_id=archetypes_by_id,
        )
    if sum(len(layout.terrain_components) for layout in artifact.layouts) != (
        EXPECTED_TOTAL_COMPONENT_COUNT
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield component total must preserve all 1,349 source pieces."
        )
    if Counter(
        contact.kind for layout in artifact.layouts for contact in layout.terrain_area_contacts
    ) != Counter({"single": 112, "separate": 112}):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source-contact kinds must preserve all 112 single-area and 112 "
            "separate-area icons."
        )
    if {
        objective.objective_id
        for layout in artifact.layouts
        for objective in layout.objectives
        if not objective.terrain_area_ids
    } != _EXPECTED_UNBOUND_OBJECTIVE_IDS:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion open-field objective inventory drifted from the source layouts."
        )
    _validate_sha256("package hash", artifact.package_hash)
    if artifact.package_hash != package_hash(artifact):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield package hash is stale."
        )
    if _reviewed_pin_is_configured(EXPECTED_PACKAGE_HASH) and (
        artifact.package_hash != EXPECTED_PACKAGE_HASH
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield package hash drifted from its reviewed pin."
        )


def package_hash(artifact: EventCompanionBattlefieldArtifact) -> str:
    payload = msgspec.to_builtins(artifact)
    if type(payload) is not dict:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield artifact payload is invalid."
        )
    payload["package_hash"] = ""
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def reviewed_pins_are_configured() -> bool:
    return all(
        _reviewed_pin_is_configured(pin)
        for pin in (
            EXPECTED_SOURCE_EXTRACTION_PAYLOAD_SHA256,
            EXPECTED_PACKAGE_HASH,
            EXPECTED_ARTIFACT_SHA256,
        )
    )


def _validate_source_coordinate_frame(frame: SourceCoordinateFrameArtifact) -> None:
    if frame.pdf_background_image_xref != SOURCE_BACKGROUND_IMAGE_XREF:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source coordinate-frame background xref drifted."
        )
    if frame.pdf_background_image_sha256 != SOURCE_BACKGROUND_IMAGE_SHA256:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source coordinate-frame background image drifted."
        )
    _validate_pdf_bounds(frame.pdf_background_bounds)
    actual_bounds = (
        frame.pdf_background_bounds.x0_points,
        frame.pdf_background_bounds.y0_points,
        frame.pdf_background_bounds.x1_points,
        frame.pdf_background_bounds.y1_points,
    )
    if any(
        not math.isclose(actual, expected, rel_tol=0.0, abs_tol=1e-6)
        for actual, expected in zip(
            actual_bounds,
            SOURCE_BACKGROUND_BOUNDS_POINTS,
            strict=True,
        )
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source coordinate-frame bounds drifted."
        )
    if (
        frame.battlefield_width_inches,
        frame.battlefield_depth_inches,
        frame.battlefield_origin,
        frame.battlefield_orientation,
        frame.coordinate_precision_decimal_places,
        frame.terrain_placement_increment_inches,
        frame.runtime_exact_seam_closure_precision_decimal_places,
    ) != (
        BATTLEFIELD_WIDTH_INCHES,
        BATTLEFIELD_DEPTH_INCHES,
        "bottom_left",
        "x_right_along_44_inch_edge_y_up_along_60_inch_edge",
        6,
        TERRAIN_PLACEMENT_INCREMENT_INCHES,
        12,
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source coordinate-frame semantics drifted."
        )


def _validate_archetypes(
    archetypes: tuple[TerrainFeatureArchetypeArtifact, ...],
) -> dict[str, TerrainFeatureArchetypeArtifact]:
    archetypes_by_id = _unique_by_id(
        "feature archetype",
        archetypes,
        lambda archetype: archetype.archetype_id,
    )
    if set(archetypes_by_id) != set(EXPECTED_ARCHETYPE_SEMANTICS):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion feature-archetype inventory drifted."
        )
    if Counter(archetype.model_kind for archetype in archetypes) != (
        EXPECTED_ARCHETYPE_MODEL_KIND_COUNTS
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion feature-archetype family counts drifted."
        )
    claimed_source_xrefs: set[int] = set()
    for archetype_id, archetype in archetypes_by_id.items():
        expected = EXPECTED_ARCHETYPE_SEMANTICS[archetype_id]
        actual_xrefs = tuple(asset.source_pdf_image_xref for asset in archetype.source_assets)
        actual = (
            actual_xrefs,
            archetype.model_kind,
            archetype.feature_kind,
            archetype.classification,
            archetype.source_component_label,
            archetype.footprint_template_id,
        )
        if actual != expected:
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion feature-archetype identity or semantics drifted."
            )
        if claimed_source_xrefs.intersection(actual_xrefs):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion source-image xrefs must belong to one archetype."
            )
        claimed_source_xrefs.update(actual_xrefs)
        _validate_non_empty_strings(archetype.name, archetype.modeling_basis)
        for asset in archetype.source_assets:
            _validate_source_image_asset(asset)
        validate_artifact_polygon(archetype.rules_footprint_polygon, within_battlefield=False)
        validate_centered_archetype_polygon(archetype.rules_footprint_polygon)
        _validate_archetype_parts(archetype)
    return archetypes_by_id


def _validate_archetype_parts(archetype: TerrainFeatureArchetypeArtifact) -> None:
    walls_by_id = _unique_by_id("archetype wall", archetype.walls, lambda wall: wall.wall_id)
    floors_by_id = _unique_by_id(
        "archetype floor",
        archetype.floors,
        lambda floor: floor.floor_id,
    )
    for wall in walls_by_id.values():
        _validate_non_empty_strings(wall.wall_id)
        _validate_finite_values(
            wall.center_x_inches,
            wall.center_y_inches,
            wall.bottom_z_inches,
            wall.width_inches,
            wall.depth_inches,
            wall.height_inches,
            wall.rotation_degrees,
        )
        if (
            wall.bottom_z_inches < 0.0
            or min(
                wall.width_inches,
                wall.depth_inches,
                wall.height_inches,
            )
            <= 0.0
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion archetype wall dimensions are invalid."
            )
    for floor in floors_by_id.values():
        _validate_non_empty_strings(floor.floor_id)
        _validate_finite_values(
            floor.center_x_inches,
            floor.center_y_inches,
            floor.bottom_z_inches,
            floor.width_inches,
            floor.depth_inches,
            floor.thickness_inches,
            floor.rotation_degrees,
        )
        if (
            floor.bottom_z_inches < 0.0
            or min(
                floor.width_inches,
                floor.depth_inches,
                floor.thickness_inches,
            )
            <= 0.0
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion archetype floor dimensions are invalid."
            )
    if archetype.model_kind == "ruin":
        floor_levels = tuple(sorted(floor.bottom_z_inches for floor in archetype.floors))
        if floor_levels not in {(0.0, 3.0), (0.0, 3.0, 6.0)}:
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion ruins require two or three three-inch floor levels."
            )
        if {wall.bottom_z_inches for wall in archetype.walls} != set(floor_levels):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion ruins require walls at every floor level."
            )
        top_level = floor_levels[-1]
        if any(
            wall.height_inches != (2.0 if wall.bottom_z_inches == top_level else 3.0)
            for wall in archetype.walls
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion ruins require continuous walls below upper floors."
            )
    elif archetype.model_kind == "dense_solid":
        if (
            archetype.floors
            or not archetype.walls
            or any(
                wall.bottom_z_inches != 0.0 or wall.height_inches <= 2.0 for wall in archetype.walls
            )
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion dense terrain requires solid bodies taller than two inches."
            )
    elif archetype.model_kind == "light_solid":
        if (
            archetype.floors
            or not archetype.walls
            or any(
                wall.bottom_z_inches != 0.0 or wall.height_inches != 2.0 for wall in archetype.walls
            )
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion light terrain requires explicit two-inch solid bodies."
            )
    else:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain archetype model kind is unsupported."
        )


def _validate_layout(
    layout: BattlefieldLayoutArtifact,
    *,
    expected_source_page: int,
    archetypes_by_id: dict[str, TerrainFeatureArchetypeArtifact],
) -> None:
    layout_number = _layout_number(layout.layout_id)
    if (
        layout.source_page,
        layout.layout_letter,
        layout.force_disposition_pair,
        layout.primary_missions,
        layout.deployment_zone_template_number,
    ) != (
        expected_source_page,
        "ABC"[layout_number - 1],
        EXPECTED_FORCE_DISPOSITION_PAIR_BY_LAYOUT[layout.layout_id],
        EXPECTED_PRIMARY_MISSIONS_BY_LAYOUT[layout.layout_id],
        EXPECTED_DEPLOYMENT_TEMPLATE_BY_LAYOUT[layout.layout_id],
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion layout page, identity, missions, or deployment template drifted."
        )
    _validate_non_empty_strings(
        layout.layout_id,
        layout.name,
        layout.source_layout_id,
        layout.attacker_edge,
        layout.defender_edge,
        *layout.force_disposition_pair,
        *layout.primary_missions,
    )
    expected_source_layout_id = _EXPECTED_SOURCE_LAYOUT_ID_OVERRIDES.get(
        layout.layout_id,
        f"gw_event_companion_v1_{layout.layout_id.replace('-', '_')}",
    )
    if layout.source_layout_id != expected_source_layout_id:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source-layout identity drifted from its stable reviewed value."
        )
    opposite_edges = {
        "north": "south",
        "south": "north",
        "east": "west",
        "west": "east",
        "north_west_corner": "south_east_corner",
        "south_east_corner": "north_west_corner",
    }
    if opposite_edges.get(layout.attacker_edge) != layout.defender_edge:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion attacker and defender edges must be opposite battlefield edges."
        )
    areas_by_id = _unique_by_id("terrain area", layout.terrain_areas, lambda area: area.area_id)
    areas_by_source_id = _unique_by_id(
        "source terrain area",
        layout.terrain_areas,
        lambda area: area.source_area_id,
    )
    expected_source_area_ids = {
        f"{layout.layout_id}-terrain-area-{area_index:02d}" for area_index in range(1, 17)
    }
    if (
        set(areas_by_source_id) != expected_source_area_ids
        or len(areas_by_id) != 16
        or Counter(area.footprint_template_id for area in layout.terrain_areas)
        != EXPECTED_TERRAIN_AREA_FAMILY_COUNTS
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion layout terrain-area family inventory drifted."
        )
    for area in layout.terrain_areas:
        _validate_terrain_area(
            area,
            layout_id=layout.layout_id,
            areas_by_id=areas_by_id,
            areas_by_source_id=areas_by_source_id,
        )
    vector_path_ids = {
        (
            area.source_pdf_extended_drawing_index_zero_based,
            area.source_pdf_seqno,
        )
        for area in layout.terrain_areas
    }
    if len(vector_path_ids) != 16:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain areas require 16 distinct source vector-path records."
        )
    components_by_id = _unique_by_id(
        "terrain component",
        layout.terrain_components,
        lambda component: component.component_id,
    )
    components_by_source_id = _unique_by_id(
        "source terrain component",
        layout.terrain_components,
        lambda component: component.source_component_id,
    )
    expected_archetype_counts = EXPECTED_COMPONENT_ARCHETYPE_COUNTS_BY_LAYOUT[layout.layout_id]
    if (
        len(components_by_id) != EXPECTED_COMPONENT_COUNT_BY_LAYOUT[layout.layout_id]
        or Counter(component.archetype_id for component in layout.terrain_components)
        != expected_archetype_counts
        or Counter(
            archetypes_by_id[component.archetype_id].model_kind
            for component in layout.terrain_components
        )
        != EXPECTED_COMPONENT_MODEL_KIND_COUNTS_BY_LAYOUT[layout.layout_id]
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion layout component inventory drifted from its source page."
        )
    for component in layout.terrain_components:
        _validate_component(
            component,
            layout_id=layout.layout_id,
            areas_by_id=areas_by_id,
            archetypes_by_id=archetypes_by_id,
        )
    validate_component_capacities(
        layout,
        areas_by_id=areas_by_id,
        components_by_id=components_by_id,
    )
    validate_component_mirror_links(
        layout,
        components_by_id=components_by_id,
        components_by_source_id=components_by_source_id,
        areas_by_id=areas_by_id,
        is_meatgrinder=layout.layout_id in _MEATGRINDER_LAYOUT_IDS,
    )
    _validate_area_classifications(
        layout.terrain_areas,
        layout.terrain_components,
        archetypes_by_id=archetypes_by_id,
    )
    validate_area_contacts(
        layout,
        areas_by_id=areas_by_id,
        areas_by_source_id=areas_by_source_id,
        expected_count=_EXPECTED_AREA_CONTACT_COUNT_BY_PAGE[layout.source_page],
    )
    validate_contact_pairs(
        "terrain-component contact",
        layout.terrain_component_contact_pairs,
        valid_ids=frozenset(components_by_id),
    )
    if (
        len(layout.terrain_component_contact_pairs)
        != (EXPECTED_COMPONENT_CONTACT_COUNT_BY_LAYOUT[layout.layout_id])
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion composite terrain-component contact inventory drifted."
        )
    validate_component_contact_semantics(
        layout,
        components_by_id=components_by_id,
    )
    _validate_objectives(layout, areas_by_id=areas_by_id)
    _validate_regions(layout)


def _validate_terrain_area(
    area: TerrainAreaArtifact,
    *,
    layout_id: str,
    areas_by_id: dict[str, TerrainAreaArtifact],
    areas_by_source_id: dict[str, TerrainAreaArtifact],
) -> None:
    area_index = _area_index(area.source_area_id, layout_id=layout_id)
    _validate_non_empty_strings(
        area.area_id,
        area.source_area_id,
        area.footprint_template_id,
        area.local_transform_basis,
        area.pose_basis,
        area.mirror_area_id,
        area.source_mirror_area_id,
    )
    if not area.area_id.startswith(f"{layout_id}-"):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion runtime terrain-area identity lost its layout context."
        )
    if area.classification not in {"dense", "light", "mixed"}:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-area classification is unsupported."
        )
    if area.local_transform not in {"identity", "mirror_y_axis"}:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-area local transform is unsupported."
        )
    if (
        type(area.source_pdf_extended_drawing_index_zero_based) is not int
        or area.source_pdf_extended_drawing_index_zero_based < 0
        or type(area.source_pdf_seqno) is not int
        or area.source_pdf_seqno < 0
        or type(area.source_pdf_vector_item_count) is not int
        or area.source_pdf_vector_item_count
        != _EXPECTED_VECTOR_ITEM_COUNT_BY_FOOTPRINT[area.footprint_template_id]
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-area vector-path provenance is invalid."
        )
    _validate_positive_xref("terrain-area source image", area.source_pdf_image_xref)
    _validate_pdf_bounds(area.source_pdf_bounds)
    _validate_pdf_affine(area.source_pdf_affine)
    _validate_sha256("terrain-area source image SHA-256", area.source_image_sha256)
    _validate_sha256("terrain-area source soft-mask SHA-256", area.source_soft_mask_sha256)
    validate_area_runtime_orientation(area)
    validate_area_pose_witness(
        area,
        is_meatgrinder=layout_id in _MEATGRINDER_LAYOUT_IDS,
        source_area_index=area_index,
    )
    if area.pose_basis != "reviewed_source_pose_with_exact_seam_closure":
        _validate_terrain_placement_coordinates(area.anchor_x_inches, area.anchor_y_inches)
    _validate_finite_values(area.rotation_degrees)
    if not _point_is_on_battlefield(area.anchor_x_inches, area.anchor_y_inches):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-area anchor is outside the battlefield."
        )
    mirror = areas_by_id.get(area.mirror_area_id)
    source_mirror = areas_by_source_id.get(area.source_mirror_area_id)
    if mirror is None or source_mirror is not mirror:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-area mirror identity is invalid."
        )
    mirror_index = _area_index(mirror.source_area_id, layout_id=layout_id)
    if (
        (area_index <= 8) == (mirror_index <= 8)
        or mirror.area_id == area.area_id
        or mirror.mirror_area_id != area.area_id
        or mirror.source_mirror_area_id != area.source_area_id
        or mirror.footprint_template_id != area.footprint_template_id
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion mirrored terrain-area semantics drifted."
        )
    if (
        layout_id in _MEATGRINDER_LAYOUT_IDS
        and area_index <= 8
        and not (
            _is_exact_sum(
                area.anchor_x_inches,
                mirror.anchor_x_inches,
                BATTLEFIELD_WIDTH_INCHES,
            )
            and _is_exact_sum(
                area.anchor_y_inches,
                mirror.anchor_y_inches,
                BATTLEFIELD_DEPTH_INCHES,
            )
            and _is_half_turn(area.rotation_degrees, mirror.rotation_degrees)
        )
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Meatgrinder terrain-area mirror pairs must preserve the accepted exact slice."
        )


def _validate_component(
    component: TerrainComponentPlacementArtifact,
    *,
    layout_id: str,
    areas_by_id: dict[str, TerrainAreaArtifact],
    archetypes_by_id: dict[str, TerrainFeatureArchetypeArtifact],
) -> None:
    _validate_non_empty_strings(
        component.component_id,
        component.source_component_id,
        component.terrain_area_id,
        component.archetype_id,
        component.local_transform_basis,
        component.pose_basis,
    )
    area = areas_by_id.get(component.terrain_area_id)
    archetype = archetypes_by_id.get(component.archetype_id)
    if area is None or archetype is None:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain component references an unknown area or archetype."
        )
    expected_component_prefix = f"{component.terrain_area_id}-component-"
    expected_source_component_prefix = f"{area.source_area_id}-component-"
    component_ordinal = component.component_id.removeprefix(expected_component_prefix)
    source_component_ordinal = component.source_component_id.removeprefix(
        expected_source_component_prefix
    )
    if (
        not component.component_id.startswith(expected_component_prefix)
        or len(component_ordinal) != 2
        or not component_ordinal.isdecimal()
        or int(component_ordinal) < 1
        or not component.source_component_id.startswith(expected_source_component_prefix)
        or source_component_ordinal != component_ordinal
        or not component.terrain_area_id.startswith(f"{layout_id}-")
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-component identity is invalid."
        )
    if archetype.footprint_template_id != area.footprint_template_id:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion component archetype does not match its area family."
        )
    if component.source_pdf_image_xref not in {
        asset.source_pdf_image_xref for asset in archetype.source_assets
    }:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion component source xref drifted from its archetype."
        )
    if component.local_transform not in {"identity", "mirror_y_axis"}:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-component local transform is unsupported."
        )
    _validate_finite_values(
        component.local_offset_x_inches,
        component.local_offset_y_inches,
        component.local_rotation_degrees,
        component.battlefield_rotation_degrees,
    )
    _validate_terrain_placement_coordinates(
        component.battlefield_center_x_inches,
        component.battlefield_center_y_inches,
    )
    if not _point_is_on_battlefield(
        component.battlefield_center_x_inches,
        component.battlefield_center_y_inches,
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-component center is outside the battlefield."
        )
    _validate_positive_xref("terrain-component source image", component.source_pdf_image_xref)
    _validate_pdf_bounds(component.source_pdf_bounds)
    _validate_pdf_affine(component.source_pdf_affine)
    validate_component_pose_witness(
        component,
        area=area,
        archetype=archetype,
        is_meatgrinder=layout_id in _MEATGRINDER_LAYOUT_IDS,
        source_area_index=_area_index(area.source_area_id, layout_id=layout_id),
    )
    validate_component_runtime_pose(component, area=area)


def _validate_area_classifications(
    areas: tuple[TerrainAreaArtifact, ...],
    components: tuple[TerrainComponentPlacementArtifact, ...],
    *,
    archetypes_by_id: dict[str, TerrainFeatureArchetypeArtifact],
) -> None:
    classifications_by_area: dict[str, set[str]] = {area.area_id: set() for area in areas}
    for component in components:
        classifications_by_area[component.terrain_area_id].add(
            archetypes_by_id[component.archetype_id].classification
        )
    for area in areas:
        classifications = classifications_by_area[area.area_id]
        expected = next(iter(classifications)) if len(classifications) == 1 else "mixed"
        if not classifications or area.classification != expected:
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion terrain-area classification does not match its components."
            )


def _validate_objectives(
    layout: BattlefieldLayoutArtifact,
    *,
    areas_by_id: dict[str, TerrainAreaArtifact],
) -> None:
    if not layout.objectives:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion layouts require a source-backed objective inventory."
        )
    objectives_by_id = _unique_by_id(
        "objective",
        layout.objectives,
        lambda objective: objective.objective_id,
    )
    _unique_by_id(
        "source objective",
        layout.objectives,
        lambda objective: objective.source_objective_id,
    )
    if (
        Counter(objective.role for objective in layout.objectives)
        != (_EXPECTED_OBJECTIVE_ROLE_COUNTS_BY_PAGE[layout.source_page])
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion objective role inventory drifted from the source page."
        )
    for objective in objectives_by_id.values():
        _validate_non_empty_strings(
            objective.objective_id,
            objective.source_objective_id,
            objective.name,
            objective.role,
            objective.source_symbol_kind,
        )
        if not objective.objective_id.startswith(
            f"{layout.layout_id}-"
        ) or not objective.source_objective_id.startswith(f"{layout.layout_id}-"):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion objective identity must retain its layout source context."
            )
        if objective.role not in {
            "attacker_home",
            "defender_home",
            "central",
            "expansion",
            "home",
        }:
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion objective role is unsupported."
            )
        _validate_finite_values(objective.x_inches, objective.y_inches)
        if any(
            not math.isclose(value * 100.0, round(value * 100.0), rel_tol=0.0, abs_tol=1e-8)
            for value in (objective.x_inches, objective.y_inches)
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion objective coordinates require 0.01-inch precision."
            )
        if not _point_is_on_battlefield(objective.x_inches, objective.y_inches):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion objective is outside the battlefield."
            )
        if len(set(objective.terrain_area_ids)) != len(objective.terrain_area_ids) or any(
            area_id not in areas_by_id for area_id in objective.terrain_area_ids
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion objective terrain-area references are invalid."
            )


def _validate_regions(layout: BattlefieldLayoutArtifact) -> None:
    deployment_by_role = _unique_by_id(
        "deployment-zone role",
        layout.deployment_zones,
        lambda region: region.role,
    )
    territory_by_role = _unique_by_id(
        "territory role",
        layout.territories,
        lambda region: region.role,
    )
    if set(deployment_by_role) != {"attacker", "defender"}:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion deployment-zone role inventory drifted."
        )
    if set(territory_by_role) != {"attacker_territory", "defender_territory"}:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion territory role inventory drifted."
        )
    validate_territory_geometry(
        template_number=layout.deployment_zone_template_number,
        territories_by_role=territory_by_role,
    )
    if layout.no_mans_land.role != "no_mans_land" or (layout.no_mans_land.owner_role is not None):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion No Man's Land identity drifted."
        )
    expected_owners = {
        "attacker": "attacker",
        "defender": "defender",
        "no_mans_land": None,
        "attacker_territory": "attacker",
        "defender_territory": "defender",
    }
    regions = (*layout.deployment_zones, layout.no_mans_land, *layout.territories)
    region_ids = _unique_by_id("battlefield-region", regions, lambda region: region.shape_id)
    if len(region_ids) != 5:
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion battlefield-region inventory drifted."
        )
    for region in regions:
        _validate_non_empty_strings(region.shape_id, region.role, region.source_kind)
        if (
            not region.shape_id.startswith(f"{layout.layout_id}-")
            or region.owner_role != expected_owners[region.role]
            or not region.polygons
        ):
            raise EventCompanionBattlefieldArtifactError(
                "Event Companion battlefield-region identity or ownership drifted."
            )
        for polygon in region.polygons:
            validate_artifact_polygon(polygon, within_battlefield=True)


def _validate_source_image_asset(asset: SourceImageAssetArtifact) -> None:
    _validate_positive_xref("source image", asset.source_pdf_image_xref)
    if (
        type(asset.pixel_width) is not int
        or asset.pixel_width <= 0
        or type(asset.pixel_height) is not int
        or asset.pixel_height <= 0
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source-image dimensions are invalid."
        )
    _validate_sha256("source image SHA-256", asset.image_sha256)
    if (asset.soft_mask_xref is None) != (asset.soft_mask_sha256 is None):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion source-image soft-mask identity is incomplete."
        )
    if asset.soft_mask_xref is not None:
        _validate_positive_xref("source-image soft mask", asset.soft_mask_xref)
        _validate_sha256("source-image soft-mask SHA-256", asset.soft_mask_sha256)


def _validate_pdf_bounds(bounds: PdfBoundsArtifact) -> None:
    _validate_finite_values(
        bounds.x0_points,
        bounds.y0_points,
        bounds.x1_points,
        bounds.y1_points,
    )
    if bounds.x1_points <= bounds.x0_points or bounds.y1_points <= bounds.y0_points:
        raise EventCompanionBattlefieldArtifactError("Event Companion PDF bounds are invalid.")


def _validate_pdf_affine(affine: PdfAffineArtifact) -> None:
    _validate_finite_values(affine.a, affine.b, affine.c, affine.d, affine.e, affine.f)
    determinant = (affine.a * affine.d) - (affine.b * affine.c)
    if math.isclose(determinant, 0.0, rel_tol=0.0, abs_tol=1e-9):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion PDF affine transform must be invertible."
        )


def _layout_number(layout_id: str) -> int:
    prefix, separator, suffix = layout_id.rpartition("-layout-")
    if (
        not separator
        or not prefix
        or suffix not in {"1", "2", "3"}
        or layout_id not in EXPECTED_LAYOUT_IDS
    ):
        raise EventCompanionBattlefieldArtifactError("Event Companion layout ID is not canonical.")
    return int(suffix)


def _area_index(area_id: str, *, layout_id: str) -> int:
    expected_prefix = f"{layout_id}-terrain-area-"
    suffix = area_id.removeprefix(expected_prefix)
    if (
        not area_id.startswith(expected_prefix)
        or len(suffix) != 2
        or not suffix.isdecimal()
        or not 1 <= int(suffix) <= 16
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain-area ID is not canonical."
        )
    return int(suffix)


def _unique_by_id[T, K](
    field_name: str,
    values: tuple[T, ...],
    identifier: Callable[[T], K],
) -> dict[K, T]:
    result: dict[K, T] = {}
    for value in values:
        key = identifier(value)
        if key in result:
            raise EventCompanionBattlefieldArtifactError(
                f"Event Companion {field_name} IDs must be unique."
            )
        result[key] = value
    return result


def _validate_non_empty_strings(*values: object) -> None:
    if any(
        type(value) is not str or not value.strip() or value != value.strip() for value in values
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion text values must be non-empty stripped strings."
        )


def _validate_finite_values(*values: object) -> None:
    if any(
        not isinstance(value, int | float) or type(value) is bool or not math.isfinite(float(value))
        for value in values
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion coordinates must be finite numbers."
        )


def _validate_terrain_placement_coordinates(*values: float) -> None:
    _validate_finite_values(*values)
    if any(
        not math.isclose(
            value / TERRAIN_PLACEMENT_INCREMENT_INCHES,
            round(value / TERRAIN_PLACEMENT_INCREMENT_INCHES),
            rel_tol=0.0,
            abs_tol=1e-9,
        )
        for value in values
    ):
        raise EventCompanionBattlefieldArtifactError(
            "Event Companion terrain placements must use 0.05-inch increments."
        )


def _validate_positive_xref(field_name: str, value: object) -> None:
    if type(value) is not int or value <= 0:
        raise EventCompanionBattlefieldArtifactError(
            f"Event Companion {field_name} xref is invalid."
        )


def _validate_sha256(field_name: str, value: object) -> str:
    _validate_non_empty_strings(value)
    if (
        type(value) is not str
        or len(value) != 64
        or any(character not in "0123456789abcdef" for character in value)
    ):
        raise EventCompanionBattlefieldArtifactError(
            f"Event Companion {field_name} must be lowercase SHA-256."
        )
    return value


def _reviewed_pin_is_configured(value: str) -> bool:
    return not value.startswith(_PENDING_REVIEWED_PIN_PREFIX)


def _require_reviewed_pin(field_name: str, value: str) -> str:
    if not _reviewed_pin_is_configured(value):
        raise EventCompanionBattlefieldArtifactError(
            f"Event Companion {field_name} still has a temporary reviewed-pin placeholder."
        )
    return _validate_sha256(field_name, value)


def _point_is_on_battlefield(x_inches: float, y_inches: float) -> bool:
    return (
        0.0 <= x_inches <= BATTLEFIELD_WIDTH_INCHES and 0.0 <= y_inches <= BATTLEFIELD_DEPTH_INCHES
    )


def _is_exact_sum(first: float, second: float, expected: float) -> bool:
    return math.isclose(first + second, expected, rel_tol=0.0, abs_tol=1e-9)


def _is_half_turn(primary_degrees: float, mirror_degrees: float) -> bool:
    return math.isclose(
        (mirror_degrees - primary_degrees) % 360.0,
        180.0,
        rel_tol=0.0,
        abs_tol=1e-9,
    )


__all__ = [
    "BATTLEFIELD_DEPTH_INCHES",
    "BATTLEFIELD_WIDTH_INCHES",
    "EXPECTED_ARCHETYPE_MODEL_KIND_COUNTS",
    "EXPECTED_ARCHETYPE_SEMANTICS",
    "EXPECTED_ARTIFACT_SHA256",
    "EXPECTED_COMPONENT_ARCHETYPE_COUNTS",
    "EXPECTED_COMPONENT_ARCHETYPE_COUNTS_BY_LAYOUT",
    "EXPECTED_COMPONENT_COUNT_BY_LAYOUT",
    "EXPECTED_COMPONENT_MODEL_KIND_COUNTS",
    "EXPECTED_COMPONENT_MODEL_KIND_COUNTS_BY_LAYOUT",
    "EXPECTED_DEPLOYMENT_TEMPLATE_BY_LAYOUT",
    "EXPECTED_FORCE_DISPOSITION_PAIR_BY_LAYOUT",
    "EXPECTED_LAYOUT_IDS",
    "EXPECTED_LAYOUT_IDS_IN_PAGE_ORDER",
    "EXPECTED_LAYOUT_ID_BY_PAGE",
    "EXPECTED_PACKAGE_HASH",
    "EXPECTED_PRIMARY_MISSIONS_BY_LAYOUT",
    "EXPECTED_SOURCE_EXTRACTION_PAYLOAD_SHA256",
    "EXPECTED_TERRAIN_AREA_FAMILY_COUNTS",
    "EXPECTED_TOTAL_COMPONENT_COUNT",
    "SOURCE_PACKAGE_ID",
    "SOURCE_PAGES",
    "SOURCE_PDF_FILENAME",
    "SOURCE_PDF_SHA256",
    "TERRAIN_PLACEMENT_INCREMENT_INCHES",
    "EventCompanionBattlefieldArtifactError",
    "event_companion_battlefield_artifact_from_json_bytes",
    "package_hash",
    "reviewed_pins_are_configured",
    "validate_event_companion_battlefield_artifact",
]
