# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

import keyword

from warhammer40k_core.engine.faction_content.manifest import (
    RuntimeContentManifestRow,
    RuntimeContentModuleFamily,
    RuntimeContentSemanticStatus,
    RuntimeContentSupportStatus,
)
from warhammer40k_core.engine.phase import GameLifecycleError
from warhammer40k_core.rules.source_packages.warhammer_40000_11th import (
    faction_detachments_2026_27,
    faction_execution_2026_27,
    faction_subrules_2026_27,
)

_BASE = "warhammer40k_core.engine.faction_content.warhammer_40000_11th"
_SOURCE_IDENTITY = faction_execution_2026_27.source_package_identity_payload()
_SOURCE_PACKAGE_ID = _SOURCE_IDENTITY["source_package_id"]
_SOURCE_PACKAGE_HASH = _SOURCE_IDENTITY["source_payload_checksum_sha256"]
_EXECUTION_RECORDS = faction_execution_2026_27.execution_records()


def generated_runtime_content_rows() -> tuple[RuntimeContentManifestRow, ...]:
    return (
        *tuple(_faction_row(row) for row in faction_detachments_2026_27.faction_rows()),
        *tuple(_detachment_row(row) for row in faction_detachments_2026_27.detachment_rows()),
        *tuple(
            _enhancement_row(row)
            for row in faction_subrules_2026_27.enhancement_rows()
            if _executable_execution_ids_for_rule(
                faction_id=row.faction_id,
                detachment_id=row.detachment_id,
                rule_id=row.enhancement_id,
                coverage_kind="detachment_enhancement",
            )
        ),
        *_pilot_runtime_content_rows(),
    )


def _faction_row(
    row: faction_detachments_2026_27.SourceFactionRow,
) -> RuntimeContentManifestRow:
    faction_module = _module_name_for_id(row.faction_id)
    execution_record_ids = _execution_ids_for(
        faction_id=row.faction_id,
        detachment_id=None,
    )
    return _row(
        content_id=row.faction_id,
        family=RuntimeContentModuleFamily.FACTION,
        source_ids=_source_ids_for(faction_id=row.faction_id, detachment_id=None),
        owner_faction_id=row.faction_id,
        owner_detachment_id=None,
        execution_record_ids=execution_record_ids,
        module_path=f"{_BASE}.{faction_module}.manifest",
        semantic_status=_semantic_status_for_execution_ids(execution_record_ids),
    )


def _detachment_row(
    row: faction_detachments_2026_27.SourceDetachmentRow,
) -> RuntimeContentManifestRow:
    faction_module = _module_name_for_id(row.faction_id)
    detachment_module = _module_name_for_id(row.detachment_id)
    execution_record_ids = _execution_ids_for(
        faction_id=row.faction_id,
        detachment_id=row.detachment_id,
    )
    return _row(
        content_id=row.detachment_id,
        family=RuntimeContentModuleFamily.DETACHMENT,
        source_ids=_source_ids_for(
            faction_id=row.faction_id,
            detachment_id=row.detachment_id,
        ),
        owner_faction_id=row.faction_id,
        owner_detachment_id=row.detachment_id,
        execution_record_ids=execution_record_ids,
        module_path=(f"{_BASE}.{faction_module}.detachments.{detachment_module}.manifest"),
        semantic_status=_semantic_status_for_execution_ids(execution_record_ids),
    )


def _enhancement_row(
    row: faction_subrules_2026_27.SourceEnhancementRow,
) -> RuntimeContentManifestRow:
    faction_module = _module_name_for_id(row.faction_id)
    detachment_module = _module_name_for_id(row.detachment_id)
    execution_record_ids = _executable_execution_ids_for_rule(
        faction_id=row.faction_id,
        detachment_id=row.detachment_id,
        rule_id=row.enhancement_id,
        coverage_kind="detachment_enhancement",
    )
    return _row(
        content_id=row.enhancement_id,
        family=RuntimeContentModuleFamily.ENHANCEMENT,
        source_ids=_source_ids_for_rule(
            faction_id=row.faction_id,
            detachment_id=row.detachment_id,
            rule_id=row.enhancement_id,
            coverage_kind="detachment_enhancement",
        ),
        owner_faction_id=row.faction_id,
        owner_detachment_id=row.detachment_id,
        execution_record_ids=execution_record_ids,
        module_path=(f"{_BASE}.{faction_module}.detachments.{detachment_module}.manifest"),
        semantic_status=_semantic_status_for_execution_ids(execution_record_ids),
    )


def _pilot_runtime_content_rows() -> tuple[RuntimeContentManifestRow, ...]:
    return (
        _row(
            content_id="plague-marines",
            family=RuntimeContentModuleFamily.DATASHEET,
            source_ids=_source_ids_for(
                faction_id="death-guard",
                detachment_id=None,
            ),
            owner_faction_id="death-guard",
            owner_detachment_id=None,
            execution_record_ids=_execution_ids_matching("death-guard:datasheet-intake"),
            module_path=f"{_BASE}.death_guard.units.plague_marines",
        ),
        _row(
            content_id="typhus",
            family=RuntimeContentModuleFamily.DATASHEET,
            source_ids=_source_ids_for(
                faction_id="death-guard",
                detachment_id=None,
            ),
            owner_faction_id="death-guard",
            owner_detachment_id=None,
            execution_record_ids=_execution_ids_matching("death-guard:datasheet-intake"),
            module_path=f"{_BASE}.death_guard.units.typhus",
        ),
        _row(
            content_id="plague-weapons",
            family=RuntimeContentModuleFamily.WARGEAR,
            source_ids=_source_ids_for(
                faction_id="death-guard",
                detachment_id=None,
            ),
            owner_faction_id="death-guard",
            owner_detachment_id=None,
            execution_record_ids=_execution_ids_matching("death-guard:datasheet-intake"),
            module_path=f"{_BASE}.death_guard.wargear.plague_weapons",
            dependency_ids=("plague-weapons:standard",),
        ),
        _row(
            content_id="plague-weapons:standard",
            family=RuntimeContentModuleFamily.WEAPON_PROFILE,
            source_ids=_source_ids_for(
                faction_id="death-guard",
                detachment_id=None,
            ),
            owner_faction_id="death-guard",
            owner_detachment_id=None,
            execution_record_ids=_execution_ids_matching("death-guard:datasheet-intake"),
            module_path=f"{_BASE}.death_guard.wargear.plague_weapons",
        ),
    )


def _row(
    *,
    content_id: str,
    family: RuntimeContentModuleFamily,
    source_ids: tuple[str, ...],
    owner_faction_id: str | None,
    owner_detachment_id: str | None,
    execution_record_ids: tuple[str, ...],
    module_path: str,
    dependency_ids: tuple[str, ...] = (),
    semantic_status: RuntimeContentSemanticStatus | None = None,
) -> RuntimeContentManifestRow:
    return RuntimeContentManifestRow(
        content_id=content_id,
        family=family,
        source_ids=source_ids,
        owner_faction_id=owner_faction_id,
        owner_detachment_id=owner_detachment_id,
        source_package_id=_SOURCE_PACKAGE_ID,
        source_package_hash=_SOURCE_PACKAGE_HASH,
        execution_record_ids=execution_record_ids,
        module_path=module_path,
        support_status=RuntimeContentSupportStatus.SUPPORTED,
        dependency_ids=dependency_ids,
        semantic_status=(
            _semantic_status_for_execution_ids(execution_record_ids)
            if semantic_status is None
            else semantic_status
        ),
    )


def _semantic_status_for_execution_ids(
    execution_record_ids: tuple[str, ...],
) -> RuntimeContentSemanticStatus:
    if not execution_record_ids:
        return RuntimeContentSemanticStatus.PLACEHOLDER
    execution_record_id_set = frozenset(execution_record_ids)
    records = tuple(
        record for record in _EXECUTION_RECORDS if record.execution_id in execution_record_id_set
    )
    if len(records) != len(execution_record_ids):
        raise GameLifecycleError(
            "Generated runtime manifest references unknown Phase 17F execution IDs."
        )
    executable_statuses = {
        faction_execution_2026_27.Phase17FExecutionStatus.EXECUTABLE_GENERIC_IR,
        faction_execution_2026_27.Phase17FExecutionStatus.EXECUTABLE_NAMED_HANDLER,
    }
    executable_count = sum(
        1 for record in records if record.execution_status in executable_statuses
    )
    if executable_count == len(records):
        return RuntimeContentSemanticStatus.IMPLEMENTED
    if executable_count > 0:
        return RuntimeContentSemanticStatus.PARTIAL
    return RuntimeContentSemanticStatus.PLACEHOLDER


def _execution_ids_for(
    *,
    faction_id: str,
    detachment_id: str | None,
) -> tuple[str, ...]:
    return tuple(
        sorted(
            record.execution_id
            for record in _EXECUTION_RECORDS
            if record.faction_id == faction_id and record.detachment_id == detachment_id
        )
    )


def _execution_ids_matching(token: str) -> tuple[str, ...]:
    return tuple(
        sorted(record.execution_id for record in _EXECUTION_RECORDS if token in record.execution_id)
    )


def _executable_execution_ids_for_rule(
    *,
    faction_id: str,
    detachment_id: str | None,
    rule_id: str,
    coverage_kind: str,
) -> tuple[str, ...]:
    executable_statuses = {
        faction_execution_2026_27.Phase17FExecutionStatus.EXECUTABLE_GENERIC_IR,
        faction_execution_2026_27.Phase17FExecutionStatus.EXECUTABLE_NAMED_HANDLER,
    }
    return tuple(
        sorted(
            record.execution_id
            for record in _EXECUTION_RECORDS
            if record.faction_id == faction_id
            and record.detachment_id == detachment_id
            and record.rule_id == rule_id
            and record.coverage_kind.value == coverage_kind
            and record.execution_status in executable_statuses
        )
    )


def _source_ids_for(
    *,
    faction_id: str,
    detachment_id: str | None,
) -> tuple[str, ...]:
    source_ids = {
        source_id
        for record in _EXECUTION_RECORDS
        if record.faction_id == faction_id and record.detachment_id == detachment_id
        for source_id in record.source_ids
    }
    return tuple(sorted(source_ids))


def _source_ids_for_rule(
    *,
    faction_id: str,
    detachment_id: str | None,
    rule_id: str,
    coverage_kind: str,
) -> tuple[str, ...]:
    source_ids = {
        source_id
        for record in _EXECUTION_RECORDS
        if record.faction_id == faction_id
        and record.detachment_id == detachment_id
        and record.rule_id == rule_id
        and record.coverage_kind.value == coverage_kind
        for source_id in record.source_ids
    }
    return tuple(sorted(source_ids))


def _module_name_for_id(identifier: str) -> str:
    module_name = identifier.replace("-", "_")
    if module_name.isidentifier() and not keyword.iskeyword(module_name):
        return module_name
    return f"content_{module_name}"
