# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

from warhammer40k_core.engine.faction_content.bundle import (
    RuntimeContentContribution,
    combine_runtime_content_contributions,
)

from .army_rule import runtime_contribution as army_rule_contribution

CONTRIBUTION_ID = "warhammer_40000_11th:world_eaters:faction_manifest:scaffold"


def runtime_contribution() -> RuntimeContentContribution:
    return combine_runtime_content_contributions(
        contribution_id=CONTRIBUTION_ID,
        contributions=(army_rule_contribution(),),
    )
