# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

from warhammer40k_core.engine.faction_content.bundle import RuntimeContentContribution

CONTRIBUTION_ID = ":".join(
    (
        "warhammer_40000_11th",
        "chaos_daemons",
        "detachment",
        "cavalcade_of_chaos",
        "enhancements",
        "scaffold",
    )
)
ENHANCEMENT_ID = "chaos-daemons:cavalcade-of-chaos:apocalyptic-steeds-upgrade"
SOUL_SHATTERING_CHARGE_ABILITY_ID = (
    "chaos-daemons:cavalcade-of-chaos:soul-shattering-charge-upgrade"
)
SOUL_SHATTERING_CHARGE_ENHANCEMENT_ID = SOUL_SHATTERING_CHARGE_ABILITY_ID
APOCALYPTIC_STEEDS_SOURCE_RULE_ID = (
    "phase17f:phase17e:enhancement:chaos-daemons:cavalcade-of-chaos:"
    "chaos-daemons:cavalcade-of-chaos:apocalyptic-steeds-upgrade"
)
SOUL_SHATTERING_CHARGE_SOURCE_RULE_ID = (
    "phase17f:phase17e:enhancement:chaos-daemons:cavalcade-of-chaos:"
    "chaos-daemons:cavalcade-of-chaos:soul-shattering-charge-upgrade"
)
APOCALYPTIC_STEEDS_RULE_IR_SOURCE_ID = (
    "gw-11e-phase17e-faction-coverage-2026-27:"
    "phase17e:enhancement:chaos-daemons:cavalcade-of-chaos:"
    "chaos-daemons:cavalcade-of-chaos:apocalyptic-steeds-upgrade:source-text"
)
SOUL_SHATTERING_CHARGE_RULE_IR_SOURCE_ID = (
    "gw-11e-phase17e-faction-coverage-2026-27:"
    "phase17e:enhancement:chaos-daemons:cavalcade-of-chaos:"
    "chaos-daemons:cavalcade-of-chaos:soul-shattering-charge-upgrade:source-text"
)
SOUL_SHATTERING_CHARGE_HOOK_ID = f"{SOUL_SHATTERING_CHARGE_SOURCE_RULE_ID}:fight-activation-ability"
SOURCE_RULE_ID = APOCALYPTIC_STEEDS_SOURCE_RULE_ID


def runtime_contribution() -> RuntimeContentContribution:
    return RuntimeContentContribution(contribution_id=CONTRIBUTION_ID)
