# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

from warhammer40k_core.engine.faction_content.bundle import RuntimeContentContribution

CONTRIBUTION_ID = "warhammer_40000_11th:chaos_daemons:detachment:cavalcade_of_chaos:rule"
SOURCE_RULE_ID = "phase17f:phase17e:chaos-daemons:cavalcade-of-chaos:rule"
RULE_IR_SOURCE_ID = (
    "gw-11e-phase17e-faction-coverage-2026-27:"
    "phase17e:chaos-daemons:cavalcade-of-chaos:rule:source-text"
)
FALL_BACK_HOOK_ID = f"{SOURCE_RULE_ID}:fall-back-eligibility"
CHAOS_DAEMONS_FACTION_ID = "chaos-daemons"
CAVALCADE_DETACHMENT_ID = "cavalcade-of-chaos"
LEGIONES_DAEMONICA = "LEGIONES DAEMONICA"
MOUNTED = "MOUNTED"


def runtime_contribution() -> RuntimeContentContribution:
    return RuntimeContentContribution(contribution_id=CONTRIBUTION_ID)
