# Generated by tools/generate_faction_content_scaffold.py.
# Regenerate with `uv run python tools/generate_faction_content_scaffold.py`.
from __future__ import annotations

from warhammer40k_core.engine.event_log import JsonValue, validate_json_value
from warhammer40k_core.engine.faction_content.bundle import RuntimeContentContribution
from warhammer40k_core.engine.phase import BattlePhase
from warhammer40k_core.engine.stratagems import (
    ENGAGED_WITH_FALL_BACK_UNIT_TARGET_POLICY_ID,
    GENERIC_RULE_IR_STRATAGEM_HANDLER_ID,
    SELECTED_TO_MOVE_TARGET_POLICY_ID,
    STRATEGIC_RESERVES_INGRESS_TARGET_POLICY_ID,
    StratagemAvailabilityKind,
    StratagemCatalogRecord,
    StratagemCategory,
    StratagemDefinition,
    StratagemRestrictionPolicy,
    StratagemTargetKind,
    StratagemTargetSpec,
    StratagemTimingDescriptor,
)
from warhammer40k_core.engine.timing_windows import TimingTriggerKind
from warhammer40k_core.rules.source_packages.warhammer_40000_11th import (
    faction_generic_ir_support_2026_27 as generic_ir_support,
)

from .rule import (
    CAVALCADE_DETACHMENT_ID,
    LEGIONES_DAEMONICA,
    MOUNTED,
)

CONTRIBUTION_ID = (
    "warhammer_40000_11th:chaos_daemons:detachment:cavalcade_of_chaos:stratagems:scaffold"
)
WARP_RIDERS_STRATAGEM_ID = "chaos-daemons:cavalcade-of-chaos:warp-riders"
WARP_RIDERS_SOURCE_ROW_ID = (
    "stratagem:chaos-daemons:cavalcade-of-chaos:chaos-daemons:cavalcade-of-chaos:warp-riders"
)
WARP_RIDERS_SOURCE_RULE_ID = f"phase17f:phase17e:{WARP_RIDERS_SOURCE_ROW_ID}"
WARP_RIDERS_RULE_IR_SOURCE_ID = (
    f"{generic_ir_support.SOURCE_PACKAGE_ID}:phase17e:{WARP_RIDERS_SOURCE_ROW_ID}:source-text"
)
SOURCE_RULE_ID = WARP_RIDERS_SOURCE_RULE_ID
WARP_RIDERS_HANDLER_ID = GENERIC_RULE_IR_STRATAGEM_HANDLER_ID
WARP_RIDERS_RECORD_ID = f"{WARP_RIDERS_SOURCE_RULE_ID}:{WARP_RIDERS_STRATAGEM_ID}"
FROM_BEYOND_THE_VEIL_STRATAGEM_ID = "chaos-daemons:cavalcade-of-chaos:from-beyond-the-veil"
FROM_BEYOND_THE_VEIL_SOURCE_ROW_ID = (
    "stratagem:chaos-daemons:cavalcade-of-chaos:"
    "chaos-daemons:cavalcade-of-chaos:from-beyond-the-veil"
)
FROM_BEYOND_THE_VEIL_SOURCE_RULE_ID = f"phase17f:phase17e:{FROM_BEYOND_THE_VEIL_SOURCE_ROW_ID}"
FROM_BEYOND_THE_VEIL_RULE_IR_SOURCE_ID = (
    f"{generic_ir_support.SOURCE_PACKAGE_ID}:phase17e:"
    f"{FROM_BEYOND_THE_VEIL_SOURCE_ROW_ID}:source-text"
)
FROM_BEYOND_THE_VEIL_RECORD_ID = (
    f"{FROM_BEYOND_THE_VEIL_SOURCE_RULE_ID}:{FROM_BEYOND_THE_VEIL_STRATAGEM_ID}"
)
INESCAPABLE_MANIFESTATIONS_STRATAGEM_ID = (
    "chaos-daemons:cavalcade-of-chaos:inescapable-manifestations"
)
INESCAPABLE_MANIFESTATIONS_SOURCE_ROW_ID = (
    "stratagem:chaos-daemons:cavalcade-of-chaos:"
    "chaos-daemons:cavalcade-of-chaos:inescapable-manifestations"
)
INESCAPABLE_MANIFESTATIONS_SOURCE_RULE_ID = (
    f"phase17f:phase17e:{INESCAPABLE_MANIFESTATIONS_SOURCE_ROW_ID}"
)
INESCAPABLE_MANIFESTATIONS_RULE_IR_SOURCE_ID = (
    f"{generic_ir_support.SOURCE_PACKAGE_ID}:phase17e:"
    f"{INESCAPABLE_MANIFESTATIONS_SOURCE_ROW_ID}:source-text"
)
INESCAPABLE_MANIFESTATIONS_RECORD_ID = (
    f"{INESCAPABLE_MANIFESTATIONS_SOURCE_RULE_ID}:{INESCAPABLE_MANIFESTATIONS_STRATAGEM_ID}"
)
MOBILE = "MOBILE"


def runtime_contribution() -> RuntimeContentContribution:
    return RuntimeContentContribution(
        contribution_id=CONTRIBUTION_ID,
        stratagem_records=(
            _warp_riders_record(),
            _from_beyond_the_veil_record(),
            _inescapable_manifestations_record(),
        ),
    )


def _warp_riders_record() -> StratagemCatalogRecord:
    return StratagemCatalogRecord(
        record_id=WARP_RIDERS_RECORD_ID,
        definition=StratagemDefinition(
            stratagem_id=WARP_RIDERS_STRATAGEM_ID,
            name="Warp-Riders",
            source_id=WARP_RIDERS_SOURCE_RULE_ID,
            command_point_cost=1,
            category=StratagemCategory.STRATEGIC_PLOY,
            when_descriptor=(
                "Your Movement phase, when a friendly LEGIONES DAEMONICA MOUNTED unit "
                "is selected to move."
            ),
            target_descriptor="That LEGIONES DAEMONICA MOUNTED unit.",
            effect_descriptor="Until the end of the phase, your unit has MOBILE.",
            restrictions_descriptor="Cavalcade of Chaos Stratagem.",
            timing=StratagemTimingDescriptor(
                trigger_kind=TimingTriggerKind.JUST_AFTER_FRIENDLY_UNIT_SELECTED_TO_MOVE,
                phase=BattlePhase.MOVEMENT,
            ),
            restriction_policy=StratagemRestrictionPolicy(),
            target_spec=StratagemTargetSpec(
                target_kind=StratagemTargetKind.FRIENDLY_UNIT,
                enumerable=True,
                target_policy_id=SELECTED_TO_MOVE_TARGET_POLICY_ID,
                required_keywords=(MOUNTED,),
                required_faction_keywords=(LEGIONES_DAEMONICA,),
            ),
            handler_id=GENERIC_RULE_IR_STRATAGEM_HANDLER_ID,
            effect_payload=_effect_payload(WARP_RIDERS_SOURCE_ROW_ID),
        ),
        availability_kind=StratagemAvailabilityKind.DETACHMENT,
        detachment_id=CAVALCADE_DETACHMENT_ID,
    )


def _from_beyond_the_veil_record() -> StratagemCatalogRecord:
    return StratagemCatalogRecord(
        record_id=FROM_BEYOND_THE_VEIL_RECORD_ID,
        definition=StratagemDefinition(
            stratagem_id=FROM_BEYOND_THE_VEIL_STRATAGEM_ID,
            name="From Beyond the Veil",
            source_id=FROM_BEYOND_THE_VEIL_SOURCE_RULE_ID,
            command_point_cost=1,
            category=StratagemCategory.STRATEGIC_PLOY,
            when_descriptor="End of the Movement phase, from the start of the battle.",
            target_descriptor="One friendly LEGIONES DAEMONICA MOUNTED unit in Strategic Reserves.",
            effect_descriptor="Your unit can be set up from Strategic Reserves.",
            restrictions_descriptor="Cavalcade of Chaos Stratagem.",
            timing=StratagemTimingDescriptor(
                trigger_kind=TimingTriggerKind.END_PHASE,
                phase=BattlePhase.MOVEMENT,
            ),
            restriction_policy=StratagemRestrictionPolicy(),
            target_spec=StratagemTargetSpec(
                target_kind=StratagemTargetKind.FRIENDLY_UNIT,
                enumerable=True,
                target_policy_id=STRATEGIC_RESERVES_INGRESS_TARGET_POLICY_ID,
                required_keywords=(MOUNTED,),
                required_faction_keywords=(LEGIONES_DAEMONICA,),
            ),
            handler_id=GENERIC_RULE_IR_STRATAGEM_HANDLER_ID,
            effect_payload=_effect_payload(FROM_BEYOND_THE_VEIL_SOURCE_ROW_ID),
        ),
        availability_kind=StratagemAvailabilityKind.DETACHMENT,
        detachment_id=CAVALCADE_DETACHMENT_ID,
    )


def _inescapable_manifestations_record() -> StratagemCatalogRecord:
    return StratagemCatalogRecord(
        record_id=INESCAPABLE_MANIFESTATIONS_RECORD_ID,
        definition=StratagemDefinition(
            stratagem_id=INESCAPABLE_MANIFESTATIONS_STRATAGEM_ID,
            name="Inescapable Manifestations",
            source_id=INESCAPABLE_MANIFESTATIONS_SOURCE_RULE_ID,
            command_point_cost=1,
            category=StratagemCategory.STRATEGIC_PLOY,
            when_descriptor=(
                "Your opponent's Movement phase, when a unit is selected to make a Fall Back "
                "move, if that unit is engaged with a friendly LEGIONES DAEMONICA MOUNTED unit."
            ),
            target_descriptor="That LEGIONES DAEMONICA MOUNTED unit.",
            effect_descriptor="That enemy unit must use the Desperate Escape mode.",
            restrictions_descriptor="Cavalcade of Chaos Stratagem.",
            timing=StratagemTimingDescriptor(
                trigger_kind=TimingTriggerKind.JUST_AFTER_ENEMY_UNIT_SELECTED_TO_FALL_BACK,
                phase=BattlePhase.MOVEMENT,
            ),
            restriction_policy=StratagemRestrictionPolicy(),
            target_spec=StratagemTargetSpec(
                target_kind=StratagemTargetKind.FRIENDLY_UNIT,
                enumerable=True,
                target_policy_id=ENGAGED_WITH_FALL_BACK_UNIT_TARGET_POLICY_ID,
                required_keywords=(MOUNTED,),
                required_faction_keywords=(LEGIONES_DAEMONICA,),
            ),
            handler_id=GENERIC_RULE_IR_STRATAGEM_HANDLER_ID,
            effect_payload=_effect_payload(INESCAPABLE_MANIFESTATIONS_SOURCE_ROW_ID),
        ),
        availability_kind=StratagemAvailabilityKind.DETACHMENT,
        detachment_id=CAVALCADE_DETACHMENT_ID,
    )


def _effect_payload(source_row_id: str) -> JsonValue:
    rule_ir = generic_ir_support.generic_rule_ir_by_coverage_descriptor_id(
        f"phase17e:{source_row_id}"
    )
    return validate_json_value({"rule_ir": rule_ir.to_payload()})
