from __future__ import annotations

from typing import TypedDict

from warhammer40k_core.engine.event_log import JsonValue


class RuntimeContentBundleSummaryPayload(TypedDict):
    activation: dict[str, JsonValue]
    selected_module_paths: list[str]
    source_package_ids: list[str]
    source_package_hashes: list[str]
    contribution_ids: list[str]
    ability_index_record_ids_by_player_id: dict[str, list[str]]
    stratagem_index_record_ids_by_player_id: dict[str, list[str]]
    ability_handler_ids: list[str]
    stratagem_handler_ids: list[str]
    rule_runtime_binding_ids: list[str]
    event_subscriptions: list[dict[str, JsonValue]]
    battle_formation_hook_ids: list[str]
    battle_round_start_hook_ids: list[str]
    turn_end_hook_ids: list[str]
    command_phase_start_hook_ids: list[str]
    fight_phase_start_hook_ids: list[str]
    unit_destroyed_hook_ids: list[str]
    battle_shock_hook_ids: list[str]
    advance_eligibility_hook_ids: list[str]
    advance_move_hook_ids: list[str]
    fall_back_hook_ids: list[str]
    movement_end_surge_hook_ids: list[str]
    reserve_arrival_distance_hook_ids: list[str]
    unit_move_completed_mortal_wound_hook_ids: list[str]
    mortal_wound_feel_no_pain_hook_ids: list[str]
    charge_declaration_hook_ids: list[str]
    shooting_target_restriction_hook_ids: list[str]
    charge_target_restriction_hook_ids: list[str]
    shooting_unit_selected_hook_ids: list[str]
    shooting_unit_selected_grant_hook_ids: list[str]
    attack_sequence_completed_hook_ids: list[str]
    shooting_end_surge_hook_ids: list[str]
    enhancement_effect_binding_ids: list[str]
    fight_activation_ability_hook_ids: list[str]
    fight_unit_selected_grant_hook_ids: list[str]
    phase_end_objective_control_hook_ids: list[str]
    stratagem_cost_choice_hook_ids: list[str]
    stratagem_cost_modifier_ids: list[str]
    unit_characteristic_modifier_ids: list[str]
    hit_roll_modifier_ids: list[str]
    wound_roll_modifier_ids: list[str]
    save_option_modifier_ids: list[str]
    movement_budget_modifier_ids: list[str]
    objective_control_modifier_ids: list[str]
    charge_roll_modifier_ids: list[str]
    weapon_profile_modifier_ids: list[str]
    faction_execution_record_ids: list[str]
    selected_execution_record_ids: list[str]
    bundle_summary_hash: str
