from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import cast

from warhammer40k_core.rules.wahapedia_schema import (
    WahapediaJsonArtifact,
    WahapediaJsonArtifactPayload,
)

DEFAULT_SOURCE_JSON_DIR = (
    Path("data")
    / "source_snapshots"
    / "wahapedia"
    / ("1" + "0" + "th-edition")
    / "2026-06-14"
    / "json"
)
DEFAULT_DATASHEET_KEYWORDS_JSON = DEFAULT_SOURCE_JSON_DIR / "Datasheets_keywords.json"
DEFAULT_FACTIONS_JSON = DEFAULT_SOURCE_JSON_DIR / "Factions.json"
DEFAULT_OUTPUT_MODULE = (
    Path("src")
    / "warhammer40k_core"
    / "rules"
    / "source_packages"
    / "warhammer_40000_11th"
    / "datasheet_keyword_lexicon_2026_06_14.py"
)
GENERATED_BY_COMMAND = "uv run python tools/generate_datasheet_keyword_lexicon.py"


def load_wahapedia_artifact(*, path: Path, expected_table: str) -> WahapediaJsonArtifact:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if type(payload) is not dict:
        raise ValueError(f"{expected_table} artifact JSON must contain an object.")
    artifact = WahapediaJsonArtifact.from_payload(cast(WahapediaJsonArtifactPayload, payload))
    if artifact.source_table != expected_table:
        raise ValueError(f"Expected {expected_table} artifact.")
    return artifact


def build_keyword_sequence_parts(
    *,
    datasheet_keywords_artifact: WahapediaJsonArtifact,
    factions_artifact: WahapediaJsonArtifact,
) -> tuple[str, ...]:
    _require_table(datasheet_keywords_artifact, "Datasheets_keywords")
    _require_table(factions_artifact, "Factions")
    keywords: set[str] = set()

    for row in datasheet_keywords_artifact.rows:
        raw_keyword = row.runtime_fields_payload()["keyword"]
        if type(raw_keyword) is not str:
            raise ValueError("Datasheets_keywords keyword field must be a string.")
        _add_keyword_sequence_part(raw_keyword, keywords)

    for row in factions_artifact.rows:
        raw_name = row.runtime_fields_payload()["name"]
        if type(raw_name) is not str:
            raise ValueError("Factions name field must be a string.")
        _add_keyword_sequence_part(raw_name, keywords)

    return tuple(sorted(keywords, key=lambda value: (-len(value), value)))


def render_datasheet_keyword_lexicon_module(
    *, parts: tuple[str, ...], source_paths: tuple[Path, ...]
) -> str:
    entries = "".join(f'    "{part}",\n' for part in parts)
    source_lines = "".join(f"#   {source_path.name}\n" for source_path in source_paths)
    return (
        "from __future__ import annotations\n\n"
        "# Generated by tools/generate_datasheet_keyword_lexicon.py.\n"
        "# Source artifacts:\n"
        f"{source_lines}"
        "# Do not edit by hand.\n\n"
        "DATASHEET_KEYWORD_SEQUENCE_PARTS_2026_06_14: tuple[str, ...] = (\n"
        f"{entries}"
        ")\n\n\n"
        "def canonical_datasheet_keyword_sequence_parts() -> tuple[str, ...]:\n"
        "    return DATASHEET_KEYWORD_SEQUENCE_PARTS_2026_06_14\n"
    )


def _require_table(artifact: WahapediaJsonArtifact, source_table: str) -> None:
    if artifact.source_table != source_table:
        raise ValueError(f"Expected {source_table} artifact.")


def _add_keyword_sequence_part(value: str, keywords: set[str]) -> None:
    normalized = _keyword_sequence_part(value)
    if normalized:
        keywords.add(normalized)


def _keyword_sequence_part(value: str) -> str:
    return " ".join(value.strip().upper().replace("-", " ").split())


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a parser keyword lexicon from source keyword artifacts."
    )
    parser.add_argument(
        "--datasheet-keywords-json",
        type=Path,
        default=DEFAULT_DATASHEET_KEYWORDS_JSON,
    )
    parser.add_argument("--factions-json", type=Path, default=DEFAULT_FACTIONS_JSON)
    parser.add_argument("--output-module", type=Path, default=DEFAULT_OUTPUT_MODULE)
    args = parser.parse_args()

    datasheet_keywords_artifact = load_wahapedia_artifact(
        path=args.datasheet_keywords_json,
        expected_table="Datasheets_keywords",
    )
    factions_artifact = load_wahapedia_artifact(
        path=args.factions_json,
        expected_table="Factions",
    )
    parts = build_keyword_sequence_parts(
        datasheet_keywords_artifact=datasheet_keywords_artifact,
        factions_artifact=factions_artifact,
    )
    module_text = render_datasheet_keyword_lexicon_module(
        parts=parts,
        source_paths=(args.datasheet_keywords_json, args.factions_json),
    )
    args.output_module.parent.mkdir(parents=True, exist_ok=True)
    args.output_module.write_text(module_text, encoding="utf-8")


if __name__ == "__main__":
    main()
