from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from pprint import pformat
from urllib.request import Request, urlopen

from warhammer40k_core.rules.mfm_source import (
    MfmFactionRecord,
    MfmIndexFaction,
    MfmSourcePackage,
    parse_mfm_faction_html,
    parse_mfm_index_html,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    ROOT
    / "src"
    / "warhammer40k_core"
    / "rules"
    / "source_packages"
    / "warhammer_40000_11th"
    / "mfm_2026_06"
)
SOURCE_URL = "https://mfm.warhammer-community.com/en/"
SOURCE_PACKAGE_ID = "gw-11e-mfm-2026-06"
SOURCE_TITLE = "Warhammer 40,000: Munitorum Field Manual"
SOURCE_VERSION = "v1.0"
SOURCE_DATE = "2026-06-17"
EXCLUDED_FACTION_IDS = ("chaos-titan-legions", "titan-legions")


class MfmImportToolError(ValueError):
    """Raised when the MFM import tool cannot build the source package."""


def main() -> None:
    args = _parse_args()
    index_html = _fetch_url(SOURCE_URL, use_curl=args.use_curl)
    factions = tuple(
        faction
        for faction in parse_mfm_index_html(index_html)
        if faction.faction_id not in EXCLUDED_FACTION_IDS
    )
    if not factions:
        raise MfmImportToolError("MFM import found no supported factions.")

    records = tuple(
        parse_mfm_faction_html(
            html=_fetch_url(_absolute_url(faction), use_curl=args.use_curl),
            faction=faction,
            source_package_id=SOURCE_PACKAGE_ID,
        )
        for faction in factions
    )
    package = MfmSourcePackage(
        source_package_id=SOURCE_PACKAGE_ID,
        source_title=SOURCE_TITLE,
        source_version=SOURCE_VERSION,
        source_date=SOURCE_DATE,
        source_url=SOURCE_URL,
        excluded_faction_ids=EXCLUDED_FACTION_IDS,
        factions=records,
    )
    output_path = args.output
    output_path.mkdir(parents=True, exist_ok=True)
    _write_package_modules(output_path=output_path, package=package)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import live Warhammer Community MFM points into a source package."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Generated Python package directory path.",
    )
    parser.add_argument(
        "--use-curl",
        action="store_true",
        help="Fetch pages through curl instead of urllib.",
    )
    return parser.parse_args()


def _fetch_url(url: str, *, use_curl: bool) -> str:
    if use_curl:
        completed = subprocess.run(
            ("curl", "-L", "--compressed", "-s", url),
            check=True,
            capture_output=True,
            text=True,
        )
        return completed.stdout
    request = Request(url, headers={"User-Agent": "warhammer40k-core-v2-mfm-importer/1"})
    with urlopen(request, timeout=30) as response:
        body = response.read()
        if type(body) is not bytes:
            raise MfmImportToolError("MFM import received a non-bytes HTTP response body.")
        return body.decode("utf-8")


def _absolute_url(faction: MfmIndexFaction) -> str:
    return "https://mfm.warhammer-community.com" + faction.url_path


def _write_package_modules(*, output_path: Path, package: MfmSourcePackage) -> None:
    expected_files = {"__init__.py"} | {
        _faction_module_name(faction) + ".py" for faction in package.factions
    }
    for path in output_path.glob("*.py"):
        if path.name not in expected_files:
            path.unlink()
    for faction in package.factions:
        module_path = output_path / (_faction_module_name(faction) + ".py")
        module_path.write_text(_faction_module_text(faction), encoding="utf-8")
    (output_path / "__init__.py").write_text(_package_init_text(package), encoding="utf-8")


def _faction_module_name(faction: MfmFactionRecord) -> str:
    module_name = faction.faction_id.replace("-", "_")
    if not module_name.isidentifier():
        raise MfmImportToolError("MFM faction ID did not resolve to a Python module name.")
    return module_name


def _faction_module_text(faction: MfmFactionRecord) -> str:
    payload = faction.to_payload()
    formatted_payload = pformat(payload, width=100, sort_dicts=False)
    return "\n".join(
        (
            "# Generated by tools/import_mfm_points.py.",
            "# Regenerate with `uv run python tools/import_mfm_points.py`.",
            "# ruff: noqa: E501",
            "from __future__ import annotations",
            "",
            "from warhammer40k_core.rules.mfm_source import MfmFactionRecordPayload",
            "",
            f"_PAYLOAD: MfmFactionRecordPayload = {formatted_payload}",
            "",
            "",
            "def faction_payload() -> MfmFactionRecordPayload:",
            "    return _PAYLOAD",
            "",
        )
    )


def _package_init_text(package: MfmSourcePackage) -> str:
    payload = package.to_payload()
    faction_modules = {
        faction.faction_id: _faction_module_name(faction) for faction in package.factions
    }
    formatted_modules = pformat(faction_modules, width=100, sort_dicts=False)
    formatted_excluded = pformat(package.excluded_faction_ids, width=100, sort_dicts=False)
    return "\n".join(
        (
            "# Generated by tools/import_mfm_points.py.",
            "# Regenerate with `uv run python tools/import_mfm_points.py`.",
            "from __future__ import annotations",
            "",
            "from importlib import import_module",
            "from typing import Final, cast",
            "",
            "from warhammer40k_core.rules.mfm_source import (",
            "    MfmFactionRecord,",
            "    MfmFactionRecordPayload,",
            "    MfmSourceError,",
            "    MfmSourcePackage,",
            "    MfmSourcePackagePayload,",
            ")",
            "",
            f'SOURCE_PACKAGE_ID: Final = "{package.source_package_id}"',
            f'SOURCE_TITLE: Final = "{package.source_title}"',
            f'SOURCE_VERSION: Final = "{package.source_version}"',
            f'SOURCE_DATE: Final = "{package.source_date}"',
            f'SOURCE_URL: Final = "{package.source_url}"',
            "SOURCE_PAYLOAD_CHECKSUM_SHA256: Final = (",
            f"    {payload['source_payload_checksum_sha256']!r}",
            ")",
            f"EXCLUDED_FACTION_IDS: Final = {formatted_excluded}",
            f"_FACTION_MODULES: Final = {formatted_modules}",
            "",
            "_FACTION_CACHE: dict[str, MfmFactionRecord] = {}",
            "_source_package_cache: MfmSourcePackage | None = None",
            "",
            "",
            "def supported_faction_ids() -> tuple[str, ...]:",
            "    return tuple(sorted(_FACTION_MODULES))",
            "",
            "",
            "def faction_record(faction_id: str) -> MfmFactionRecord:",
            "    cached = _FACTION_CACHE.get(faction_id)",
            "    if cached is not None:",
            "        return cached",
            "    module_name = _FACTION_MODULES.get(faction_id)",
            "    if module_name is None:",
            '        raise MfmSourceError("MFM faction_id was not found in generated package.")',
            '    module = import_module(f"{__name__}.{module_name}")',
            "    payload = cast(MfmFactionRecordPayload, module.faction_payload())",
            "    record = MfmFactionRecord.from_payload(payload)",
            "    _FACTION_CACHE[faction_id] = record",
            "    return record",
            "",
            "",
            "def source_package() -> MfmSourcePackage:",
            "    global _source_package_cache",
            "    if _source_package_cache is None:",
            "        _source_package_cache = MfmSourcePackage.from_payload(",
            "            _source_package_payload()",
            "        )",
            "    return _source_package_cache",
            "",
            "",
            "def _source_package_payload() -> MfmSourcePackagePayload:",
            "    return {",
            '        "source_package_id": SOURCE_PACKAGE_ID,',
            '        "source_title": SOURCE_TITLE,',
            '        "source_version": SOURCE_VERSION,',
            '        "source_date": SOURCE_DATE,',
            '        "source_url": SOURCE_URL,',
            '        "excluded_faction_ids": list(EXCLUDED_FACTION_IDS),',
            '        "factions": [',
            "            faction_record(faction_id).to_payload()",
            "            for faction_id in supported_faction_ids()",
            "        ],",
            '        "source_payload_checksum_sha256": SOURCE_PAYLOAD_CHECKSUM_SHA256,',
            "    }",
            "",
        )
    )


if __name__ == "__main__":
    main()
