from __future__ import annotations

import json
import os
import runpy
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Protocol, cast

REPO_ROOT = Path(__file__).resolve().parents[2]
CLIENT_ROOT = REPO_ROOT / "conformance" / "typescript"
FORBIDDEN_CLIENT_TOKENS = (
    "warhammer40k_core.engine",
    "warhammer40k_core.adapters.local_session",
    "GameLifecycle",
    "DecisionController",
)


class _ContractRootPreparer(Protocol):
    def __call__(self, *, committed_root: Path, regenerated_root: Path) -> None: ...


class _ContractTreeDrift(Protocol):
    def __call__(self, *, committed_root: Path, regenerated_root: Path) -> tuple[str, ...]: ...


def test_phase18m_typescript_client_does_not_import_engine_internals() -> None:
    client_files = tuple(sorted((CLIENT_ROOT / "src").rglob("*.ts")))
    assert client_files
    violations: list[str] = []
    for path in client_files:
        source = path.read_text(encoding="utf-8")
        for forbidden in FORBIDDEN_CLIENT_TOKENS:
            if forbidden in source:
                violations.append(f"{path.relative_to(REPO_ROOT).as_posix()}: {forbidden}")
    assert violations == []


def test_phase18m_typescript_modules_respect_new_module_size_budget() -> None:
    oversized = {
        path.relative_to(REPO_ROOT).as_posix(): len(path.read_text(encoding="utf-8").splitlines())
        for path in sorted((CLIENT_ROOT / "src").rglob("*.ts"))
        if len(path.read_text(encoding="utf-8").splitlines()) > 1_500
    }
    assert oversized == {}


def test_phase18m_package_pins_generation_typecheck_and_live_conformance() -> None:
    package = json.loads((CLIENT_ROOT / "package.json").read_text(encoding="utf-8"))
    assert package["engines"] == {"node": ">=24"}
    scripts = package["scripts"]
    assert "../../contracts/openapi.yaml" not in scripts["conformance"]
    assert scripts["generate"].startswith("node scripts/generate-models.mjs")
    assert scripts["check"] == "npm run check:generated && npm run typecheck"
    assert scripts["test:unit"] == "tsx --test src/**/*.test.ts"
    assert scripts["test"] == "npm run check && npm run test:unit && npm run conformance"
    generated = (CLIENT_ROOT / "src" / "generated" / "openapi.ts").read_text(encoding="utf-8")
    assert "This file was auto-generated by openapi-typescript." in generated
    assert "export interface paths {" in generated
    assert "$defs:" not in generated


def test_external_contract_check_regenerates_into_an_isolated_tree_before_validation() -> None:
    builder = (REPO_ROOT / "scripts" / "build_external_contract.py").read_text(encoding="utf-8")

    assert "if args.check:\n        _verify_regenerated_contract_bundle()" in builder
    assert "_clean_generated_contract_outputs(contract_root=CONTRACT_ROOT)" in builder
    assert "tempfile.TemporaryDirectory" in builder
    assert "_prepare_regenerated_contract_root(" in builder
    assert "_contract_tree_drift(" in builder
    assert "External contract generated files drifted" in builder


def test_external_contract_regeneration_discards_orphan_generated_fixtures(
    tmp_path: Path,
) -> None:
    committed_root = tmp_path / "committed" / "contracts"
    orphan = committed_root / "examples" / "projections" / "retired-orphan.json"
    orphan.parent.mkdir(parents=True)
    orphan.write_text('{"retired": true}\n', encoding="utf-8")
    manual_contract = committed_root / "README.md"
    manual_contract.write_text("manual contract input\n", encoding="utf-8")
    manifest = committed_root / "manifest.json"
    manifest.write_text('{"stale": true}\n', encoding="utf-8")
    regenerated_root = tmp_path / "regenerated" / "contracts"
    scripts_directory = REPO_ROOT / "scripts"
    sys.path.insert(0, str(scripts_directory))
    try:
        namespace = runpy.run_path(str(scripts_directory / "build_external_contract.py"))
    finally:
        sys.path.remove(str(scripts_directory))
    prepare = cast(_ContractRootPreparer, namespace["_prepare_regenerated_contract_root"])
    contract_tree_drift = cast(_ContractTreeDrift, namespace["_contract_tree_drift"])

    prepare(committed_root=committed_root, regenerated_root=regenerated_root)

    assert not (regenerated_root / "examples").exists()
    assert not (regenerated_root / "manifest.json").exists()
    assert (regenerated_root / "README.md").read_text(encoding="utf-8") == (
        "manual contract input\n"
    )
    assert "removed: contracts/examples/projections/retired-orphan.json" in contract_tree_drift(
        committed_root=committed_root,
        regenerated_root=regenerated_root,
    )


def test_external_contract_write_mode_removes_orphan_generated_fixture(
    tmp_path: Path,
) -> None:
    output_root = tmp_path / "write-mode-output"
    contract_root = output_root / "contracts"
    shutil.copytree(REPO_ROOT / "contracts", contract_root)
    orphan_relative_path = Path("examples/projections/retired-orphan.json")
    orphan = contract_root / orphan_relative_path
    shutil.copyfile(
        contract_root / "examples/projections/initial_setup_view_player1.json",
        orphan,
    )
    environment = os.environ.copy()
    environment["_WARHAMMER40K_EXTERNAL_CONTRACT_OUTPUT_ROOT"] = str(output_root)

    completed = subprocess.run(
        (sys.executable, str(REPO_ROOT / "scripts/build_external_contract.py")),
        cwd=REPO_ROOT,
        env=environment,
        check=False,
        capture_output=True,
        encoding="utf-8",
    )

    assert completed.returncode == 0, completed.stderr or completed.stdout
    assert not orphan.exists()
    manifest = json.loads((contract_root / "manifest.json").read_text(encoding="utf-8"))
    orphan_manifest_path = orphan_relative_path.as_posix()
    assert orphan_manifest_path not in manifest["example_schema_by_path"]
    assert orphan_manifest_path not in manifest["file_sha256"]
    verified = subprocess.run(
        (sys.executable, str(REPO_ROOT / "scripts/build_external_contract.py"), "--check"),
        cwd=REPO_ROOT,
        env=environment,
        check=False,
        capture_output=True,
        encoding="utf-8",
    )
    assert verified.returncode == 0, verified.stderr or verified.stdout


def test_phase18m_executable_client_is_operation_bound_without_identifier_conventions() -> None:
    contract = (CLIENT_ROOT / "src" / "contract.ts").read_text(encoding="utf-8")
    client = (CLIENT_ROOT / "src" / "client.ts").read_text(encoding="utf-8")
    scenario = (CLIENT_ROOT / "src" / "scenario.ts").read_text(encoding="utf-8")
    type_fixture = (
        CLIENT_ROOT / "src" / "type-fixtures" / "session-command-envelope.type-test.ts"
    ).read_text(encoding="utf-8")

    assert 'import type { components, paths } from "./generated/openapi.js";' in contract
    assert 'CreateSessionOperation["requestBody"]' in contract
    assert 'ExecuteSessionCommandOperation["requestBody"]' in contract
    assert "as SessionCommandEnvelope" not in scenario
    assert "request<T>" not in client
    assert 'split(":", 1)' not in scenario
    assert 'playerId === "player-b"' not in scenario
    assert type_fixture.count("@ts-expect-error") == 3


def test_phase18m_cross_backend_replay_uses_canonical_semantic_comparison() -> None:
    main = (CLIENT_ROOT / "src" / "main.ts").read_text(encoding="utf-8")
    scenario = (CLIENT_ROOT / "src" / "scenario.ts").read_text(encoding="utf-8")
    canonical_test = (CLIENT_ROOT / "src" / "canonical-json.test.ts").read_text(encoding="utf-8")

    assert "replay_raw" not in main
    assert "replay_raw" not in scenario
    assert "canonicalJsonSha256(closedReplay.body)" in scenario
    for field in (
        "source_identity",
        "decision_records",
        "event_records",
        "projection_checkpoints",
    ):
        assert field in main
    assert "ignores JSON property order and whitespace" in canonical_test
