from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CLIENT_ROOT = REPO_ROOT / "conformance" / "typescript"
FORBIDDEN_CLIENT_TOKENS = (
    "warhammer40k_core.engine",
    "warhammer40k_core.adapters.local_session",
    "GameLifecycle",
    "DecisionController",
)


def test_phase18m_typescript_client_does_not_import_engine_internals() -> None:
    client_files = tuple(sorted((CLIENT_ROOT / "src").rglob("*.ts")))
    assert client_files
    violations: list[str] = []
    for path in client_files:
        source = path.read_text(encoding="utf-8")
        for forbidden in FORBIDDEN_CLIENT_TOKENS:
            if forbidden in source:
                violations.append(f"{path.relative_to(REPO_ROOT).as_posix()}: {forbidden}")
    assert violations == []


def test_phase18m_typescript_modules_respect_new_module_size_budget() -> None:
    oversized = {
        path.relative_to(REPO_ROOT).as_posix(): len(path.read_text(encoding="utf-8").splitlines())
        for path in sorted((CLIENT_ROOT / "src").rglob("*.ts"))
        if len(path.read_text(encoding="utf-8").splitlines()) > 1_500
    }
    assert oversized == {}


def test_phase18m_package_pins_generation_typecheck_and_live_conformance() -> None:
    package = json.loads((CLIENT_ROOT / "package.json").read_text(encoding="utf-8"))
    assert package["engines"] == {"node": ">=24"}
    scripts = package["scripts"]
    assert "../../contracts/openapi.yaml" not in scripts["conformance"]
    assert scripts["generate"].startswith("node scripts/generate-models.mjs")
    assert scripts["check"] == "npm run check:generated && npm run typecheck"
    assert scripts["test:unit"] == "tsx --test src/**/*.test.ts"
    assert scripts["test"] == "npm run check && npm run test:unit && npm run conformance"
    generated = (CLIENT_ROOT / "src" / "generated" / "openapi.ts").read_text(encoding="utf-8")
    assert "This file was auto-generated by openapi-typescript." in generated
    assert "export interface paths {" in generated
    assert "$defs:" not in generated


def test_phase18m_executable_client_is_operation_bound_without_identifier_conventions() -> None:
    contract = (CLIENT_ROOT / "src" / "contract.ts").read_text(encoding="utf-8")
    client = (CLIENT_ROOT / "src" / "client.ts").read_text(encoding="utf-8")
    scenario = (CLIENT_ROOT / "src" / "scenario.ts").read_text(encoding="utf-8")
    type_fixture = (
        CLIENT_ROOT / "src" / "type-fixtures" / "session-command-envelope.type-test.ts"
    ).read_text(encoding="utf-8")

    assert 'import type { paths } from "./generated/openapi.js";' in contract
    assert 'CreateSessionOperation["requestBody"]' in contract
    assert 'ExecuteSessionCommandOperation["requestBody"]' in contract
    assert "as SessionCommandEnvelope" not in scenario
    assert "request<T>" not in client
    assert 'split(":", 1)' not in scenario
    assert 'playerId === "player-b"' not in scenario
    assert type_fixture.count("@ts-expect-error") == 3


def test_phase18m_cross_backend_replay_uses_canonical_semantic_comparison() -> None:
    main = (CLIENT_ROOT / "src" / "main.ts").read_text(encoding="utf-8")
    scenario = (CLIENT_ROOT / "src" / "scenario.ts").read_text(encoding="utf-8")
    canonical_test = (CLIENT_ROOT / "src" / "canonical-json.test.ts").read_text(encoding="utf-8")

    assert "replay_raw" not in main
    assert "replay_raw" not in scenario
    assert "canonicalJsonSha256(closedReplay.body)" in scenario
    for field in (
        "source_identity",
        "decision_records",
        "event_records",
        "projection_checkpoints",
    ):
        assert field in main
    assert "ignores JSON property order and whitespace" in canonical_test
