from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CLIENT_ROOT = REPO_ROOT / "conformance" / "typescript"
FORBIDDEN_CLIENT_TOKENS = (
    "warhammer40k_core.engine",
    "warhammer40k_core.adapters.local_session",
    "GameLifecycle",
    "DecisionController",
)


def test_phase18m_typescript_client_does_not_import_engine_internals() -> None:
    client_files = tuple(sorted((CLIENT_ROOT / "src").rglob("*.ts")))
    assert client_files
    violations: list[str] = []
    for path in client_files:
        source = path.read_text(encoding="utf-8")
        for forbidden in FORBIDDEN_CLIENT_TOKENS:
            if forbidden in source:
                violations.append(f"{path.relative_to(REPO_ROOT).as_posix()}: {forbidden}")
    assert violations == []


def test_phase18m_typescript_modules_respect_new_module_size_budget() -> None:
    oversized = {
        path.relative_to(REPO_ROOT).as_posix(): len(path.read_text(encoding="utf-8").splitlines())
        for path in sorted((CLIENT_ROOT / "src").rglob("*.ts"))
        if len(path.read_text(encoding="utf-8").splitlines()) > 1_500
    }
    assert oversized == {}


def test_phase18m_package_pins_generation_typecheck_and_live_conformance() -> None:
    package = json.loads((CLIENT_ROOT / "package.json").read_text(encoding="utf-8"))
    assert package["engines"] == {"node": ">=24"}
    scripts = package["scripts"]
    assert "../../contracts/openapi.yaml" not in scripts["conformance"]
    assert scripts["generate"].startswith("node scripts/generate-models.mjs")
    assert scripts["check"] == "npm run check:generated && npm run typecheck"
    assert scripts["test"] == "npm run check && npm run conformance"
    generated = (CLIENT_ROOT / "src" / "generated" / "openapi.ts").read_text(encoding="utf-8")
    assert "This file was auto-generated by openapi-typescript." in generated
    assert "export interface paths {" in generated
